### ISSUE TITLE
Ability to remove the clock

### ISSUE THREAD

**Issue by SilverCory** [Raymo111/i3lock-color#10]
This would be pretty awesome.

**Comment by PandorasFox** [comment]
I'll look into that later this week. Shouldn't be too difficult.

**Comment by PandorasFox** [comment]
Um wait, hold on, did I ever put my clock implementation on github? I don't think I pushed that branch ever.

I had a branch that had a clock (similar to [this fork](https://github.com/Lixxia/i3lock) of i3lock), but I don't think that there's any clock functionality in my fork.

I'll probably add an option for that sooner or later, when I get time. University has been keeping me busy.

**Comment by PandorasFox** [comment]
I'll likely apply [this commit](https://github.com/ravinrabbid/i3lock-clock/commit/0de3a411fa5249c3a4822612c2d6c476389a1297) with some tweaks to my fork later, with some options for setting the text colors. 

I may also look into some other goodies, like setting the `cairo_font_face`, which'll be interesting.

**Comment by SilverCory** [comment]
Sexy! Much appreciated.

**Comment by PandorasFox** [comment]
I now have a [new branch](https://github.com/chrjguill/i3lock-color/tree/clock) that has the clock feature in it. I've just got a basic port of that other guy's patch and I'll work on improving it some over the next week or so (might do fonts, and will likely allow for custom time strings).

if you want to try out the `clock` branch, just `checkout -b clock && make i3lock`, then test with `./i3lock -k` . It should work fine.

**Comment by PandorasFox** [comment]
Alright, I've finalized the custom time strings and a couple other things. I think it should be mostly bug free and I'm happy with the end result; I'm going to merge it in to the main branch in a few and then begin work on some other options.
