### ISSUE TITLE
Feature request: pipe images

### ISSUE THREAD

**Issue by sylveon** [Raymo111/i3lock-color#100]
By being able to pipe images to i3lock, I would be able to completely avoid having to save a temporary screenshot in my locking script. A common syntax for this is `-` as filename, so the feature would work like this:

    maim | i3lock -i -

That command would take a screenshot of the desktop and then use it as i3lock-color background.

**Comment by PandorasFox** [comment]
I've debated doing this in the past, but I haven't been able to figure out the best way to do it. (There'd need to be some reading into a buffer and arbitrarily resizing it since we won't know how large the file stream is).

I have a long flight today, so I'll probably work on it then, some, after I finally merge upstream.

**Comment by sylveon** [comment]
You could write a C-compatible wrapper around C++'s std::vector.

Something like this (extern C'd obviously):

```cpp
void *new_vector() {
    return new std::vector<T>;
}

void push_back(void *vector, T item) {
    static_cast<std::vector<T> *>(vector)->push_back(item);
}

T *data(void *vector) {
     return static_cast<std::vector<T> *>(vector)->data();
}

delete_vector(void *vector) {
     delete vector;
}
```

**Comment by vifino** [comment]
I'm interested in this, but not for PNGs or anything, but Farbfeld images.
http://tools.suckless.org/farbfeld/

I wrote an image glitching filter (https://github.com/shinyblink/ff-glitch) and something to add an image on top of another one (https://github.com/shinyblink/ff-overlay), all using farbfeld stuff.
Would be nice if I can dismiss the conversion to pngs and use the nice farbfeld format full-time.

I'm probably gonna take a look at the code of this, but I am not sure how i3lock is structured so I'll take a while for me to find a place to implement farbfeld image support.

The actual format is very easy to parse though, so once I find that hook, it should be pretty easy.

With `png2ff` it should be very easy to convert png streams (ie catted or outputted via another utility) to farbfeld streams, which are much simpler to parse.

**Comment by PandorasFox** [comment]
This was rolled up in #120
