### ISSUE TITLE
Feature: 2FA

### ISSUE THREAD

**Issue by guyest** [Raymo111/i3lock-color#108]
## Summary
PAM makes it easy to implement secure authentication for UNIX systems. We shouldn't have to abandon KISS to maintain 2FA best practices in the workplace (or even at home if you err on the side of caution). If display managers can do it, so can the little screen-locker `i3lock-color`. What needs to be done to make `i3lock-color` compatible with multi-factor authentication in stacked PAM modules?

## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail): Feature Request
</pre>

## Current Behavior
As it stands, i3lock-color (like any other fork of i3lock I have seen) can only handle a single entry to the PAM stack. Obviously, this breaks if you want to get back into your X session when your system is set up with more than one level of authentication.

## Expected Behavior
I expect PAM to be PAM, without anything getting in the way. If PAM wants more auth tokens, I expect to be able to acquiesce. 

## Reproduction Instructions
Set up your PAM modules to require any form of multi-factor authentication, then proceed to lock yourself out of your system. (Pro tip: remember your root login, and maybe try this in a separate VT via, e.g., Ctrl-Alt-F2)

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 2.11.1
</pre>
To be fair, I am running the non-color fork at the moment, but `i3lock-color` seems more active and I get a better sense of a productive outcome here, so here I am. 

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[ ] Built from source yourself
[x] Other (Please describe in detail): community/i3lock on Arch Linux (yes, not i3lock-color, but see above.)
</pre>

**Comment by PandorasFox** [comment]
This is a major feature request that I likely won't have the spare resources to implement into i3lock-color. Please make raise this issue at [i3/i3lock](https://github.com/i3/i3lock) and if they implement it, I will pull and integrate it.

**Comment by PandorasFox** [comment]
I'm graduating university and am about to start working at Google full-time in January and I am unsure what the status of this project is. I may simply only have time for maintenance, or legal might prohibit me from working on this in the future - a semester or two ago, I would've taken a crack and this and then looked into making a pull upstream and contributing back.

**Comment by h3ct0rjs** [comment]
@PandorasFox  congratz for getting the job at Google. I've read that you could talk with your pm or manager about the open source projects. It would be great if the official i3lock will integrate this version. I really like this version :smile: , the only bad thing is  how to handle the memory leaks front the fonts. 

It would be very interesting if you write a blog post or something similar describing who you are, motivations....also describing your path to getting the job at Google.

**Comment by PandorasFox** [comment]
> It would be great if the official i3lock will integrate this version

Pretty unlikely, since their philosophy tends to be 'minimize attack surfaces' which goes counter to 'customize things for aesthetics'. Features like 2FA would be something I can see being accepted upstream.

> It would be very interesting if you write a blog post or something similar describing who you are, motivations....also describing your path to getting the job at Google.

I might at some point! It's been a pretty weird journey through college, but setting up a blog takes more time than I want to put into it right now haha

**Comment by h3ct0rjs** [comment]
@PandorasFox  ok, please send me an email if you do it :smile:

**Comment by guyest** [comment]
@PandorasFox: Understood, best of luck in your new job! Interestingly enough, the solution I have landed on for the moment is using an opensource project out of Google, [xsecurelock](https://github.com/google/xsecurelock).

**Comment by h3ct0rjs** [comment]
@guygma  where Can I find the implementation with i3, xsecurelock supports 2fa :wolf:

**Comment by guyest** [comment]
@h3ct0rjs There isn't something like an "i3lock-xsecurelock" fork of i3lock if that is what you mean... `xsecurelock` is just a drop-in replacement for `i3lock`. You can choose to use one or the other of them. I require 2FA on my company network and `xsecurelock was just the best option I found implementing that.

**Comment by h3ct0rjs** [comment]
thanks for the clarification @guygma  :+1:
