### ISSUE TITLE
Feature request: configuration file

### ISSUE THREAD

**Issue by abelfodil** [Raymo111/i3lock-color#111]
Instead of defining program configuration when launching it, we would instead define a set of properties that would be used by default and stored somewhere like `~/.config/i3/lock`.

This would make the configuration more readable and maintainable than a bash script.
It would also remove the need of defining a bash script (or a long command).

**Comment by PandorasFox** [comment]
#78

unlikely to be implemented as it would require too much complexity and I'm trying to differ from upstream as little as possible to make maintenance easier.
