### ISSUE TITLE
Option to pick which monitor it shows on

### ISSUE THREAD

**Issue by itszaen** [Raymo111/i3lock-color#112]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>
Please check out the issue here: https://github.com/pavanjadhaw/betterlockscreen/issues/94
(same story) I have a two monitor setup, and currently it's not letting me pick which one it shows the lock on.

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.12.c-non-git © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[ ] Built from source yourself
[x] Other (Please describe in detail)
</pre>
GitHub BetterLockScreen: https://github.com/pavanjadhaw/betterlockscreen/issues/94
AUR page: https://aur.archlinux.org/packages/betterlockscreen/

**Comment by PandorasFox** [comment]
https://github.com/PandorasFox/i3lock-color/blob/master/i3lock.1#L115

**Comment by itszaen** [comment]
Oops, sorry about that. Thanks for your time though. :)
