### ISSUE TITLE
Disabling asan for git builds?

### ISSUE THREAD

**Issue by l29ah** [Raymo111/i3lock-color#114]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior
i3lock-color is built with an address sanitizer unconditionally, wasting my precious joules and heating my pants.

## Expected Behavior
There should be a way to disable it without monkey-patching the build system.

**Comment by PandorasFox** [comment]
This is something that I've been meaning to look into. I don't have too much experience with GNU autotools and haven't really been able to devise a 'good' solution for how to enable debug builds easily.

**Comment by Raymo111** [comment]
@l29ah Mind elaborating?

**Comment by Raymo111** [comment]
Please reopen this issue if and when you add more details.
