### ISSUE TITLE
Update keyboard layout indicator on change

### ISSUE THREAD

**Issue by webknjaz** [Raymo111/i3lock-color#115]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

When I hit hotkeys for switching layout it changes but the on-screen indicator doesn't.

## Expected Behavior

When switch keyboard layout, the on-screen indicator should show the new layout instead of the old one.

## Reproduction Instructions
`--keylayout 2`

## Environment
Output of `i3lock --version`:
<pre>
i3lock version:
i3lock: version 2.12.c-non-git © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[ ] Built from source yourself
[x] `gig` Gentoo Overlay
</pre>

**Comment by PandorasFox** [comment]
What hotkey(s) do you have for changing the keyboard layout? I was under the impression that this wasn't possible (ie i3lock would process whatever keypress and would not propagate it).

It should be a relatively easy fix for this; I'll move the logic for this to be done on every draw tick. It might slow down the locker drawing a bit, but it'll only happen when the keylayout is being displayed and that's okay.

**Comment by webknjaz** [comment]
Right Shift + Left Shift

**Comment by webknjaz** [comment]
```console
$ cat /etc/X11/xorg.conf.d/00-keyboard.conf
# Read and parsed by systemd-localed. It's probably wise not to edit this file
# manually too freely.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us,ua,cz"
        Option "XkbOptions" "grp:alt_space_toggle,grp:shifts_toggle,grp:sclk_toggle,compose:ralt,compose:rwin"
EndSection
```

**Comment by PandorasFox** [comment]
Ah, alright. I wasn't aware that keylayout switching was even doable at that level - I'd assumed it was only possible to bind a keysym to exec something.

I should be able to use that to test this out; thanks!

**Comment by andremarcais** [comment]
For me the language is not correct when it first locks either. It just uses the first language in the keyboard layout list. If I `setxkbmap -layout 'us,fr'` the locker tells me I'm using US keyboard even if I switch to the French layout prior to locking (using Shift+Shift like webknjaz).

**Comment by Raymo111** [comment]
@andremarcais can you send a screencap of master vs 167? @webknjaz if you don't mind can you also help verify? It's just that this isn't something I can test (on KDE and not i3)

**Comment by ivoshm** [comment]
If it helps I tested @andremarcais patched version on Manjaro XFCE (US and CZ keyboards, switched by LeftShift-RightShift) and everything looks OK.

**Comment by Raymo111** [comment]
@ivoshm awesome, thanks!

**Comment by andremarcais** [comment]
[out.mpg.gz](https://github.com/Raymo111/i3lock-color/files/4724368/out.mpg.gz)

Here's a gziped screen capture where I used master and 167. I did change the keyboard layout in both using shift+shift. The password used in the video is ``t0t0``.

**Comment by Raymo111** [comment]
@andremarcais awesome! Glad to see it works!
