### ISSUE TITLE
Support for tty lock switching

### ISSUE THREAD

**Issue by rgcv** [Raymo111/i3lock-color#117]
**Quick disclaimer:** I understand if i3lock-color won't pull changes from i3lock until a proper release is made over at ![i3/i3lock](https://github.com/i3/i3lock). If so, this issue isn't worth much and I'd expect the feature may be integrated later on when it actually gets released.

## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

Currently, i3lock-color is pretty much in tandem with i3lock. However, in the mainline, as of i3/i3lock@dcfcba3ed48587f607dd37f08dcf55b731dc2303, i3lock supports the capability of locking tty switching, a feature lacking in i3lock-color. A rather important one, might I add, IMHO.
By using the `-l` option, when the screen is locked, it won't enable the user from switching to a tty until the screen is unlocked.

## Expected Behavior

That i3lock-color be capable of supporting this feature. However, currently, the user can freely switch tty from the lock screen.

## Environment
Output of `i3lock --version`:
<pre>
i3lock: aur-966b2b1 (2019-04-02, branch "tags/aur-966b2b1") © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (i3lock-color-git)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by PandorasFox** [comment]
i3lock-color is now synced with upstream
