### ISSUE TITLE
.././configure: line 6328: syntax error near unexpected token `XCB,'

### ISSUE THREAD

**Issue by hg8** [Raymo111/i3lock-color#118]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior
Can not build i3lock-color

## Expected Behavior
Successful build

## Reproduction Instructions
```
$ ./configure
checking for library containing iconv_open... none required
.././configure: line 6328: syntax error near unexpected token `XCB,'
.././configure: line 6328: `PKG_CHECK_MODULES(XCB, xcb xcb-xkb xcb-xinerama xcb-randr xcb-composite)'
```

The same happen when trying using AUR (which should take care of the dependencies).
Any idea what I am missing ? Thanks.

<pre>
[x] AUR package (which one?)
[x] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by AUTplayed** [comment]
did you try installing `xcb-util-xrm` ?

**Comment by hg8** [comment]
Thanks for your help. Yes I installed it.

```
$ pacman -Qs xcb
local/libxcb 1.13.1-1
local/libxkbcommon-x11 0.8.4-1
local/xcb-proto 1.13-2
local/xcb-util 0.4.0-2
local/xcb-util-cursor 0.1.3-2
local/xcb-util-errors 1.0-3
local/xcb-util-image 0.4.0-2
local/xcb-util-keysyms 0.4.0-2
local/xcb-util-renderutil 0.3.9-2
local/xcb-util-wm 0.4.1-2
local/xcb-util-xrm 1.3-1
```

**Comment by hg8** [comment]
Silly mistake again, I was searching for missing `xcb` lib but turned out I was missing `pkgconf`.

```
sudo pacman -S pkgconf
```

And all is working now.
