### ISSUE TITLE
FreeBSD PAM config file causes PAM_AUTHINFO_UNAVAIL

### ISSUE THREAD

**Issue by jwfh** [Raymo111/i3lock-color#119]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

Using FreeBSD 12.0-RELEASE, `i3lock-color` fails _all_ login attempts, even with the correct password.

## Expected Behavior

`i3lock-color` should reveal the X desktop and quit when a correct password is entered.

## Reproduction Instructions

System: FreeBSD 12.0-RELEASE amd64

```fish
git clone https://github.com/PandorasFox/i3lock-color; and cd i3lock-color
autoreconf -i
set -x MAKE gmake
./configure
```

Edit `i3lock.c` to print the result of `pam_authenticate()` if debugging is enabled, then compile.

```fish
sudo gmake install
i3lock --debug
```

Kill `i3lock` (I just SSHed into the machine and did a `killall(1)`). Terminal output will show that PAM is returning 9 from `pam_authenticate()`, which is defined in `include/security/_pam_types.h` as meaning `PAM_AUTHINFO_UNAVAIL` (underlying authentication service cannot retrieve authentication information).

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.12.c-8-g966b2b1 (2019-04-02, branch "master") © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[x] Built from source yourself (on FreeBSD 12.0-RELEASE with gmake)
[ ] Other (Please describe in detail)
</pre>

**Comment by PandorasFox** [comment]
I'm not too familiar with PAM on freebsd (or freeBSD at all) - does i3lock exhibit this? I feel this may be caused by not having the PAM module installed, but I'm not really sure.

**Comment by jwfh** [comment]
It turns out that PAM was not seeing the `/usr/local/etc/pam.d/i3lock` configuration file. With that said, once the issue was resolved `i3lock` was exhibiting the opposite behavior: allowing access with _any_ password. The same thing happened with the regular `i3lock`. It did not happen with the FreeBSD port of `i3lock`, however that was minimally helpful as I'm unable to read 2000+ lines of Makefile to see what they may have done differently.

A little research indicated that the problem may be because `i3lock` is running as me when I invoke it, PAM looks at the UID of the `i3lock` process and immediately approves the auth request without even wanting a password. A [FreeBSD bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=181525) for the FreeBSD port of the regular `i3lock` from 2013 mentions a similar thing. 

In this bug report, it is suggested to change the i3lock PAM configuration as follows:

```
/usr/loca/etc/pam.d/i3lock:
- auth include login
+ auth include system
```

I don't think this will fix anything as the `login` PAM config includes the `system` file.

Rather the suggestion to [flag the setuid bit on the `i3lock` binary](https://github.com/freebsd/freebsd-ports/blob/e7782880300826a1f4652d49a3a37d77546be52b/x11/i3lock/Makefile#L34) seems to have worked. The `Makefile` produced by `./configure` didn't do this on my system (Should it have done it? Is that necessary on Linux too? I would imagine it is.). 

To fix the problem on my computer I modified `i3lock.c` as follows:

```c
@@ -2073,6 +2072,9 @@ int main(int argc, char *argv[]) {
     struct ev_check *xcb_check = calloc(sizeof(struct ev_check), 1);
     struct ev_prepare *xcb_prepare = calloc(sizeof(struct ev_prepare), 1);
 
+    int current_uid = getuid();
+    setuid(0);
+
     ev_io_init(xcb_watcher, xcb_got_event, xcb_get_file_descriptor(conn), EV_READ);
     ev_io_start(main_loop, xcb_watcher);
 
@@ -2112,5 +2114,7 @@ int main(int argc, char *argv[]) {
     set_focused_window(conn, screen->root, stolen_focus);
     xcb_aux_sync(conn);
 
+    setuid(current_uid);
+
     return 0;
 }
```

And after running `sudo gmake install` (remember that on BSD-like operating systems, `make` is BSD make and GNU make &mdash; the default on Linux systems &mdash; is `gmake`... should this distinction be made more explicit to help BSD users compile? They'd also need to set $MAKE to "gmake" before running `./configure`), I then added the setuid bit to the binary:

```fish
sudo chmod u+s (which i3lock)
```

---

Should those changes to the source code be necessary? Also I am wary of using `setuid(0)`. I'd like the least code running as root as possible. With that change in place if the root user (hypothetically, not that one would log in as root and start X for day-to-day anything) was logged in and locked the screen the same behavior of PAM allowing any password would return, this time allowing anyone into the root account. As the requirement isn't necessarily to wield rootly powers to execute the `pam_authenticate(3)` call, just that the user running the locker is not the same user whose screen is being locked, I wonder if running this as the nobody user would work. 

I'm closing the issue for now as my problem is fixed but I look forward to hearing your thoughts on what I've written above.

**Comment by PandorasFox** [comment]
I'd also be wary of running it as root - it shouldn't need to, and it's weird pam behaves in that way.

Would it be possible to run the screenlocker as a dummy user that has restricted filesystem access, etc? Since in that case pam would hopefully run correctly, and there's the added benefit of running the screenlocker with less privs than your regular user.

As for why the freeBSD port works.... I haven't a clue what might be done differently; honestly, I don't really fully understand the automate system that's used now (nor do I particularly want to), unfortunately. I'd just chalk this up to a weird freeBSD PAM quirk - it kinda does seem to me that the probably-intended solution is to have the screenlocker run as an untrusted user and not the logged in user.
