### ISSUE TITLE
Support for MPRIS integration

### ISSUE THREAD

**Issue by t1meshift** [Raymo111/i3lock-color#124]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior
`i3lock-color` supports media key passthrough, but there is no way to display a track playing now.

## Expected Behavior
`i3lock-color` could be run with specific keys so a lockscreen would be shown with a current player info taken from MPRIS, e.g. player state, artist and track name. Maybe even album cover, but a user should take care about a placeholder in case a cover isn't present by MPRIS.

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version aur-564e34b (2019-05-31, branch "tags/aur-564e34b") © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (i3lock-color-git)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by PandorasFox** [comment]
Too complex; would increase the attack surface too much / make it harder to ensure the locker is safe against crashes.
