### ISSUE TITLE
Lock screen dies when started from systemd with -k

### ISSUE THREAD

**Issue by consnop** [Raymo111/i3lock-color#125]
## This issue is a....
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior
When launched by systemd with the `-k` option for displaying the clock, it dies right after showing up on screen without any output even with the `--debug` option. 
I'll be honest, idk 100% if this is a i3lock-color issue, but I have no idea what else could be causing this.

## Expected Behavior
Lock screen doesn't die when launched by systemd with the `-k` option. 

## Reproduction Instructions
Save the following unit file as /etc/systemd/system/suspend@.service : 
```
[Unit]
Description=lock screen
Before=suspend.target

[Service]
User =  <username>
Type = forking
Environment = DISPLAY=:0
ExecStart = i3lock -k

[Install]
WantedBy=suspend.target
```
enable the service with `systemctl enable suspend@<username>`
suspend computer

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.12.c-non-git © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

Where'd you get i3lock-color from?
<pre>
[ ] AUR package (which one?)
[ ] Built from source yourself
[x] Other (Please describe in detail)
</pre>
Open Build Service: https://build.opensuse.org/package/show/home%3Adigitaltomm/i3lock-color

**Comment by PandorasFox** [comment]
It sounds like the issue is related to the suspending while i3lock is running with the clock - my guess is something related to the event loop for redrawing the screen?

Unless you can provide more info (stack trace? anything logged in journalctl / systems?) there's not much to do.

**Comment by consnop** [comment]
I get this in journalctl 
```
Control process exited, code=exited, status=1/FAILURE
Failed with result 'exit-code'.
```
The same thing happens when I set it to run after suspend.
I'm not sure how I would go about getting the stack trace.
It also reports memory leaks, but that happens without the clock as well and doesn't seem to cause any other problems.

**Comment by PandorasFox** [comment]
Try making sure that you make a build without ASAN enabled, since that can slow things down significantly and might be causing issues with suspending with it enabled.
