### ISSUE TITLE
i3lock-color slow when verifying my password

### ISSUE THREAD

**Issue by adriencarbonaro** [Raymo111/i3lock-color#127]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

When i3lock is verifying my password, it is much slower than the videos and GIF that I find either in Reddit or here. (1-2 secs)

## Reproduction Instructions

Usually, I use other more complicated scripts to set the indicator but to reproduce as simple as possible, I just type `i3lock`

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 2.12.c-2-g1d58ce0 (2018-10-06, branch "master") © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[x] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by PandorasFox** [comment]
did you compile with ASAN enabled or no?
