### ISSUE TITLE
free(): double free detected in tcache 2

### ISSUE THREAD

**Issue by joehillen** [Raymo111/i3lock-color#130]
I noticed this output while messing with i3lock-color. Thought you would like to know:

```
free(): double free detected in tcache 2
```

**Comment by PandorasFox** [comment]
Looks like that's an issue in glibc. What glibc version so you have / what system are you running?

**Comment by joehillen** [comment]
Archlinux glibc version 2.29-4

**Comment by PandorasFox** [comment]
Cool. One last question - assuming you installed this from the AUR, could you reinstall the package? if it's linked against an older version of glibc it can cause some problems like that; relinking it might fix this.

**Comment by joehillen** [comment]
I've reinstalled `i3lock-color-git`. It did not solve the issue. It takes about 5 retries of opening and closing i3lock for the message to appear. Here are the options I'm launching i3lock with:

```
i3lock \
    -c 262626 \
    --ignore-empty-password \
    --show-failed-attempts \
    --composite \
    --insidecolor=00000022 \
    --ringcolor=262626ff \
    --linecolor=00000000 \
    --keyhlcolor=ffffffff \
    --ringvercolor=00000000 \
    --separatorcolor=222222ff \
    --insidevercolor=0000ffff \
    --ringwrongcolor=00000000 \
    --insidewrongcolor=ff0000ff \
    -i $IMG
```

**Comment by Raymo111** [comment]
@joehillen I've made a bunch of build edits, check if this is still an issue? If it is, reopen it.

**Comment by joehillen** [comment]
Still happening. It takes a couple tries, but it happens after the screen is unlocked.

**Comment by Raymo111** [comment]
@joehillen Intersting. I'm not as cool as Fox, so can you give a little more explanation? What did you do exactly?

**Comment by joehillen** [comment]
I'm trying to repro in valgrind with debug symbols. I'll let you know if I can successfully capture it.

**Comment by joehillen** [comment]
Also, I haven't been able to repro this on my laptop. It only happens on my desktop where I have 3 monitors. That might be part of it.

**Comment by Raymo111** [comment]
Hmm, interesting. If you do repro it, update me :)

**Comment by Raymo111** [comment]
If this issue is reproduced we can reopen and revisit.
