### ISSUE TITLE
Merge from upstream

### ISSUE THREAD

**Issue by Raymo111** [Raymo111/i3lock-color#134]
@PandorasFox i3-lock-color is currently 4 commits behind i3lock. Mind if I attempt a merge? (I'll transfer everything they added manually)

**Comment by PandorasFox** [comment]
Sure thing! I haven't been at my desktop for a while; it looks like there's a merge conflict somewhere - I imagine it's just in the tty switching revert, so nothing too weird.

**Comment by Raymo111** [comment]
Ok. The thing is that upstream is using flags that we're using, so even if it can be auto-merged, we don't want that. I'll copy the changes over sometime today and we can work from there.
Very interested in helping you maintain this project, since it's my favorite lockscreen :)
