### ISSUE TITLE
Support control characters (\n, \r, \b, \t)

### ISSUE THREAD

**Issue by kingelilol** [Raymo111/i3lock-color#138]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

Newline results in a little box (same size as other chars)
## Expected Behavior

It should result in a second/third… line.
## Reproduction Instructions

`i3lock --force-clock --datestr="%A %n %d"`
```
i3lock --greetertext="line 1
line 2" 
```

## Environment
Output of `i3lock --version`:
<pre>
i3lock version:
i3lock: version aur-eabfff3 (2019-09-27, branch "tags/aur-eabfff3") © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (which one?)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>
AUR package: i3lock-color-git

**Comment by Raymo111** [comment]
You should be using `\n` for all newlines in strings. If you intend on using multiple lines in a bash script use `\` at the end of the line.

**Comment by cmsxbc** [comment]
I‘m suffering this too. However, it's not a issue of i3lock.it's something from "the toy text api" of cairo, the graphics library that i3lock used. As cairo's document said, [cairo-text](https://www.cairographics.org/manual/cairo-text.html).There is no way to implement what we wanted with current api.
Fortunately, cairo supply some low level api to control how one character drawed on context. ([cairo-show-text-glyphs](https://www.cairographics.org/manual/cairo-text.html#cairo-show-text-glyphs)) So it's possiable to do it.
1. The first way is to use pango, which is recommend by cairo. But i had no idea to solve a fccache assert error while i tried using it.
2. And then I had made a patch with these low level api, which is ugly but works for '\n' (and just, not work for other control character).If any still need it, [my-patch](https://github.com/cmsxbc/i3lock-color/commit/e34e190483a9eca959b2570384a9825b5de36347)

**Comment by TheScreechingBagel** [comment]
neither newline nor /n work

**Comment by Raymo111** [comment]
It's `\n`, and are you trying it on the PR or on Master? It's not merged yet.

**Comment by TheScreechingBagel** [comment]
Yes, sorry, noticed the pr a bit late and was replying more to the earlier messages
