### ISSUE TITLE
Some seconds are skipped (slow update?)

### ISSUE THREAD

**Issue by ghost** [Raymo111/i3lock-color#139]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

The clock displays (e. g.) `22:15:42`, then `22:15:44`. Simply it skips some seconds (and some are maybe displayed too late).

## Expected Behavior

`22:15:42` → `22:15:43` → `22:15:44`

## Reproduction Instructions

`i3lock-color` is started with:
<pre>
B='#00000000'  # blank
C='#00000088'  # clearish
D='#aaaaaacc'  # default
T='#ffffffee'  # text
K='#ffff00bb'  # keypress
W='#cc4400bb'  # wrong
V='#aaaa00bb'  # verifying

i3lock \
-e \
-f \
-m \
-t \
-n \
\
--blur 10 \
--screen=0 \
\
--insidevercolor=$C \
--ringvercolor=$V \
\
--insidewrongcolor=$C \
--ringwrongcolor=$W \
\
--insidecolor=$B \
--ringcolor=$D \
--linecolor=$B \
--separatorcolor=$D \
\
--verifcolor=$T \
--wrongcolor=$T \
--timecolor=$T \
--datecolor=$T \
--layoutcolor=$T \
--keyhlcolor=$K \
--bshlcolor=$W \
\
--indpos="x+w-(w/4):y+h/8+85" \
\
--force-clock \
--indicator \
--timestr="%_H:%_M:%_S" \
--timesize=75 \
--time-align=1 \
--timepos="x+w/8:y+h/8+95" \
--datestr="%a %_d %b %_Y" \
--datesize=30 \
--date-align=1 \
--datepos="tx:ty+40" \
--keylayout 0 \
--layoutsize=20 \
--layout-align=1 \
--layoutpos="tx:ty-70" \
--modsize=20 \
\
--bar-indicator \
--bar-orientation=horizontal \
--bar-position="y+h/8" \
--bar-color=$C \
--bar-width=100 \
--bar-direction=2 \
--bar-step=10 \
--bar-max-height=40 \
--bar-base-width=150 \
\
--veriftext="Wait..." \
--wrongtext="Try again" \
--noinputtext="..." \
</pre>

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.12.c (2018-10-02, branch "tags/2.12.c") © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (which one?)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>
i3lock-color

**Comment by PandorasFox** [comment]
It's unfortunately a side-effect of redrawing the canvas every tick. It's a holdover from i3lock since it's an acceptable cost there - the only ticks are on keystrokes and timeouts.

I did some work to alleviate this a while ago, but couldn't really completely eliminate this when using the bar display :(

**Comment by ghost** [comment]
Ah, that's sad. 😢 Thanks for the info.
