### ISSUE TITLE
Please add an option to specify the circle radius

### ISSUE THREAD

**Issue by JaneSmith** [Raymo111/i3lock-color#14]
It would make a huge difference to me if there was a simple command line option to specify the radius of the circle. Currently this seems to be hardcoded in as `#define BUTTON_RADIUS`.

For my resolution, the default radius makes the unlock indicator look very tiny on my screen, which is not pleasing to the eye. Making it customisable would also give me more freedom to align the unlock indicator with a background image.

**Comment by PandorasFox** [comment]
I've been poking at it some and it'll require more work. For now, the really hacky stuff I just did in 5 minutes is up [here](https://github.com/chrjguill/i3lock-color/tree/radius). 

It works, but the text isn't aligned at all.

_Eventually_, I want to break out the ricing/drawing options into a config file, and leave the arguments for things like nofork/beep/show failed attempts. Ideally there'd be a way to just specify themes and look at some XDG dirs.

If I get that far, it wouldn't be difficult to just read in more stuff from a config file for text positioning and stuff. For now, specifying more arguments to handle things is... rapidly getting gross, and something I'm trying to avoid.

**Comment by PandorasFox** [comment]
Implemented in 6ec7c668cfc101b89076aa6226714397a66065a1
