### ISSUE TITLE
i3lock-color turns the screen on when moving a disabled mouse

### ISSUE THREAD

**Issue by l29ah** [Raymo111/i3lock-color#140]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior
i3lock-color handles events from disabled mouse, turning screen on at night annoyingly.

## Expected Behavior
i3lock-color not handling input from disabled input devices.

## Reproduction Instructions
```
xset dpms force off; xinput set-prop "Powered by Avago Laser Gaming Mouse" "Device Enabled" 0; i3lock
```

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.12.c-57-geabfff3 (2019-09-27, branch "git-r3/HEAD") © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[ ] Built from source yourself
[x] Other (Please describe in detail)
</pre>
Gentoo ebuild from ::booboo.

**Comment by PandorasFox** [comment]
Does this happen on upstream i3lock? This sounds like it'd be an issue there too, since I've  never touched the input event handling ever.
