### ISSUE TITLE
How many command line options are there?

### ISSUE THREAD

**Issue by alpha0mega96** [Raymo111/i3lock-color#141]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>
No readable doc available about how to use new options

## Current Behavior

There's no man page document created when one compiles i3lock-color.
If I use i3lock --help, I see "refer to man page" but that doesn't describe any of the new options available in i3lock-color.

## Expected Behavior

The help message gives some more info or a link to info about each new option.
Otherwise, the man page be updated.

## Reproduction Instructions

<pre>
i3lock --help
</pre>
OR
<pre>
man i3lock
</pre>
## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 2.12.c (2018-10-02, branch "tags/2.12.c") © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[x] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by PandorasFox** [comment]
https://github.com/PandorasFox/i3lock-color/blob/master/i3lock.1

This is the manpage. When you `sudo make install` or install the package from a package manager, it should be available (if it isn't - try changing the values you pass into `./configure`, i.e. `./configure --prefix=/usr --sysconfdir=/etc`).
