### ISSUE TITLE
ASAN: ==73446==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.

### ISSUE THREAD

**Issue by Naveenkumarpeteti** [Raymo111/i3lock-color#145]
Hi, I am trying to build (using GCC 6.3 version) my code with Asan (using flag:-fsanitize=address) , Building my whole code involves c files , .so files and executables. 

I am able to build my code successfully. But when i try to run my code, it failed with issue :

 [==73446==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.](url)

i am trying to set LD_PRELOAD = /path/<libasan.so> in my environment file. 
I am hitting the issue :- [ERROR: ld.so: object '/libs/common/gcc/v6.3.0/lib/libasan.so' from LD_PRELOAD cannot be preloaded: ignored.](url)

I would like to follow first approach of 'link runtime to your application', How could we do that ? Does it needs to deals with adding some flags to gcc while building code ?

Please let me know if you need any other info.

**Comment by Raymo111** [comment]
Can you clarify the issue?

**Comment by Raymo111** [comment]
You can reopen this issue upon clarifying.

**Comment by eadwu** [comment]
Basically https://github.com/Raymo111/i3lock-color/issues/114. I'm pretty sure ASAN should mostly be used as a runtime when developing and not in production. Becomes an issue as well when you use an alternate malloc.

**Comment by Raymo111** [comment]
I have no experience with ASAN, and since from now on I'm providing a binary in releases this shouldn't matter for production use.
