### ISSUE TITLE
CRITICAL SECURITY ISSUE regarding touchscreen gestures

### ISSUE THREAD

**Issue by Raymo111** [Raymo111/i3lock-color#146]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

Touchscreen gestures are passed through to to KDE and can be used to kill i3lock.

## Expected Behavior

All touchscreen gestures are captured and blocked

## Reproduction Instructions

In KDE, set custom command `pkill i3lock` for a touchscreen edge gesture. Start i3lock, do the gesture and i3lock will be killed.

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: `aur-eabfff3 (2019-09-27, branch "tags/aur-eabfff3")`
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[ ] Built from source yourself
[x] Other (One or the other, can't remember)
</pre>

**Comment by PandorasFox** [comment]
I don't have a touchscreen device to test this against, but this doesn't really seem like an i3lock problem - there's a lot of ways you can shoot yourself in the foot with i3lock (have a media key be bound to kill i3lock, bam).

In either case: this is likely an upstream issue ([i3/i3lock](https://github.com/i3/i3lock)), but I think a better solution is to just disable touchscreen gestures prior to locking & restore them afterwards via a lock script. I can't really think of any easy or standard way to grab touchscreen devices and capture all their events.
