### ISSUE TITLE
FR: Voice authentication support

### ISSUE THREAD

**Issue by seendsouza** [Raymo111/i3lock-color#153]
@Raymo111 has been working on [voice authentication for Linux](https://github.com/Raymo111/voiceprint). When that works, i3lock-color should be able to display the generated passphrase that the user needs to speak in order to login. It can also have customizable audio visualization when the user is speaking (maybe based on [cava](https://github.com/karlstav/cava)).

**Comment by Raymo111** [comment]
@seendsouza Excellent idea! For when we get the PAM module done. We could maybe make addons :)

**Comment by Raymo111** [comment]
https://github.com/Raymo111/voiceprint Implemented!! Just add `auth sufficient pam_voiceprint.so` to `/etc/pam.d/i3lock`.
