### ISSUE TITLE
timecolor doesn't seem to do anything?

### ISSUE THREAD

**Issue by qazip** [Raymo111/i3lock-color#154]
I am running the following command:

`i3lock -c 040c0d --clock --timecolor=f1fff000`

However, timecolor doesn't seem to do anything? I want to have a darkish background, with clock and the clock/time color in a off-white. However, running that command, I cannot see the clock.

**Comment by bendardenne** [comment]
This color code is fully transparent. 

Try changing the trailing 00's with a higher alpha value, e.g.  `f1fff0ff`

**Comment by Raymo111** [comment]
@qazip Exactly as @bendardenne said.
