### ISSUE TITLE
Wrong information about build script

### ISSUE THREAD

**Issue by Mef45** [Raymo111/i3lock-color#157]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

In order to build i3lock-color, we need to run the `./build.sh` file

## Expected Behavior

Instruction says, that we should run `./make.sh`
```
chmod +x make.sh
./make.sh
```
## Reproduction Instructions

Download source files from `Release` page / Do `git clone`.

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: i3lock: version 2.12.c.2 (2020-04-18) © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[x] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
@Mef45 Thanks for pointing that out! Fixed.
