### ISSUE TITLE
Ability to remove (replace) displayed text

### ISSUE THREAD

**Issue by niraami** [Raymo111/i3lock-color#16]
I guess the title is self explanatory.
Could you add a few new arguments like `vertext` and `wrongtext` and replace the hard coded text in `draw_image()` with variables?

**Comment by PandorasFox** [comment]
Will poke at it some when I have time; I can't do too much work over the break.

I think I looked at doing something similar to this (displaying custom text / etc) but handling string length well and figuring out what works best will require some work (as well as aligning, etc)

**Comment by niraami** [comment]
I can see the problems in aligning (and currently don't have any solutions..), but string length can be one of two things:

1. Static, who wants to print a whole paragraph on their screen anyway?
2. Defined by the circle radius and allocated along with all other options ( I believe in main()? )

Both of these solutions are with assumptions that the text will still be inside the circle, though If you mean  something like custom text displayed on the side as a feed (or maybe even more custom), that changes things.

Though, IMO the second solution seems the most rational.
Also, I would help with commits but I'm currently working on my own project, so I'm kinda busy.

**Comment by PandorasFox** [comment]
Yeah, this is on the back burner for the holidays since I've got some other stuff going on, but hopefully I can get around to it before my next semester picks up.

I may go with static to begin with (something like 64 chars seems reasonable, I think), and then work on tweaking circle radius (I think that's #14?) and figure something out with that.

Ideally I'd also have text positioning as well (i.e. x/y coordinates, placing it under the circle, etc)

**Comment by PandorasFox** [comment]
Thanks to @Jereviendrai, there's some nice text positioning stuff now, so I may borrow those and work on this next week.

**Comment by niraami** [comment]
That's great to hear! I hope you can find the time to work on it.
And, well, now that I'm here, I'm gonna finally open a new issue because on both my Arch installations your i3lock stopped working... like a while back :D

**Comment by PandorasFox** [comment]
tfw github doesn't have a 'crying' reaction

**Comment by PandorasFox** [comment]
Implemented in 6ec7c668cfc101b89076aa6226714397a66065a1
