### ISSUE TITLE
In the release tag, what the `c` stand for?

### ISSUE THREAD

**Issue by PetrusZ** [Raymo111/i3lock-color#163]
## This issue is a....

<pre>
[ ] Bug
[X] Other kind of issue (Please describe in detail)
</pre>

For example, in `2.12.c.4`, what's the meaning of `c`?

It's confuses me when I try to pack i3lock-color on Gentoo.

In Gentoo Linux, package name following rules in https://devmanual.gentoo.org/ebuild-writing/file-format/index.html#file-naming-rules.

So `2.12.c.4` should be named as `2.12_rc4` or `2.12_p4`?

Thanks.

**Comment by Raymo111** [comment]
@PetrusZ The c stands for color in i3lock-color. Upstream rarely releases, so the upstream version is 2.12 rn. Since I release quite often, I can differentiate the c releases from upstream. If you're trying to package for gentoo I guess just remove the c? hope this clears it up for you.

**Comment by PetrusZ** [comment]
OK, thanks for your explanation.
