### ISSUE TITLE
Ringradius and textsize properties don't work

### ISSUE THREAD

**Issue by tiberiu-dascal** [Raymo111/i3lock-color#164]
## Cannot change ring radius or text size
<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior
When --ringradius is set to a value, nothing happens.
When --textsize is enabled and set to a value, i3lock-color doesn't work 
These two options should work as per your "README / Additional features in i3lock-color".

## Expected Behavior
Setting the above mentioned values should show different layout of the ring and the text size should change

## Reproduction Instructions
run `i3lock --textsize=12 --ringradius=200`
```
➜ i3lock --textsize=12
i3lock: unrecognized option '--textsize=12'
i3lock: Syntax: i3lock [-v] [-n] [-b] [-d] [-c color] [-u] [-p win|default] [-i image.png] [-t] [-e] [-f]
Please see the manpage for a full list of arguments.
```

```
➜ i3lock --ringradius=200
i3lock: unrecognized option '--ringradius=200'
i3lock: Syntax: i3lock [-v] [-n] [-b] [-d] [-c color] [-u] [-p win|default] [-i image.png] [-t] [-e] [-f]
Please see the manpage for a full list of arguments.

```

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.12.c.1 (2020-03-10, branch "tags/2.12.c.1") © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

Where'd you get i3lock-color from?

<pre>
[X] AUR package (which one?) community/i3lock-color 
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
@tibix Please read the manpage before filing an issue like this, via the `man i3lock` command. The options to manipulate text size are delegated to each individual text item. The option for the radius of the ring is just `--radius`, not `--ringradius`. Read the documentation!

**Comment by tiberiu-dascal** [comment]
Thank you @Raymo111. Message received and I would have appreciated it more, without the condescending tone. Some of us are less versed in Linux than others, and it does not help when some one looks down on you for not knowing something.
Still, thank you for taking the time to look into my miss-informed bug report and, taking the time to reply back. All the best.

**Comment by Raymo111** [comment]
@tibix sorry if I came across as harsh or condescending, that wasn't my intention. I was just bewildered as to where you came up with those options, and I wanted to stress the importance of reading documentation.
