### ISSUE TITLE
Change layouttext color in different states

### ISSUE THREAD

**Issue by LRDPRDX** [Raymo111/i3lock-color#165]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Suggestion)
</pre>

## Current Behavior

The color of the layout text doesn't change in different states. The layout text is displayed all the time while other text may change its color. So it is kind of color dissonance.
## Expected Behavior

It would be great if it was possible to change the color of the layout text in different states (`no input`/`wrong`/`verifying` etc) (or at least don't display it in all the states but `default`).

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.12.c.4 (2020-05-18) © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2020 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[x] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
@LRDPRDX can you be more specific? What do you mean the other text is different but layout is the same. Send screenshots as well if possible.

**Comment by LRDPRDX** [comment]
In the gif below the layout text always is in the same color while other text changes. And I don't see how I could change it (layout's color) accordingly.

![lock](https://user-images.githubusercontent.com/26169258/83345256-4983e500-a33b-11ea-95ae-bcfb6cbd0882.gif)

**Comment by Raymo111** [comment]
@LRDPRDX the issue with this is that the wrongtext is its own color, and all the static texts (time, numlock etc.) are their own color. If we have an option to update each text in each of the different states I think we'll have an explosion of too many options.

**Comment by LRDPRDX** [comment]
Don't you think about having a config file for `i3lock-color`?

**Comment by Raymo111** [comment]
@LRDPRDX i3lock and i3lock-color are designed to be simple, lightweight programs. For me,  have a script containing 3 different usecases of i3lock, bound to 3 different keybinds. A config file may seem nice, but people can easily keybind or alias their lock commands, and I would need 3 different config files for my use case and still the same script. Perhaps a config file is useful for some programs, but I don't see the current need for it with i3lock-color.
