### ISSUE TITLE
White blink before image display on lock

### ISSUE THREAD

**Issue by romzie** [Raymo111/i3lock-color#166]
## This issue is a....

<pre>
[ ] Bug
[X] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

Command used: `i3lock -i /tmp/img.png`
When using i3lock apt package : works as expected (see [gif](https://gfycat.com/pleasedhoarseadamsstaghornedbeetle))
When installing i3lock-color : there is a white blink before the image display (see [gif](https://gfycat.com/naivespotlesskiwi))

## Expected Behavior

No white blink with i3lock-color

## Reproduction Instructions
I am using Ubuntu 20.04 (DE is Regolith 1.4, WM is i3-gaps)
Installed i3lock using `sudo apt install i3lock`, then recorded the first gif above
Then cloned this repo, built and installed it from source before recording the second gif
Image used was generated using 
    `scrot -z -o /tmp/img.jpg && convert -scale 20% -scale 500% /tmp/img.jpg /tmp/img.png`

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: version 2.12.c.4 (2020-05-18)
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[X] Built from source yourself (commit 720e2b4cfce703b870788de283be21e50c22096f)
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
@romzie i3lock-color has to render a bunch of stuff more than i3lock, so it's showing the default background color (white) for an instant (images can have transparency so the bg color has to be rendered first). The best way to fix this is to set the background color to something unnoticeable, like black (`-c 000000`). If there's no transparency in your image or you don't mind transparency then you can go for a transparent bg color (`-c 00000000`). Hope this helps!

Note to self: probably related to #159.

**Comment by romzie** [comment]
Thank you for the quick reply, using a transparent background color indeed is enough for my use case. We can close this issue now I guess.

**Comment by Raymo111** [comment]
No worries. Awesome, glad I could help!
