### ISSUE TITLE
[question] multiple monitors, use screenshot per monitor?

### ISSUE THREAD

**Issue by andersfylling** [Raymo111/i3lock-color#169]
## This issue is a....

<pre>
[x] Performance
</pre>

## Current Behavior

I can only specify one screenshot for all my monitors.

## Expected Behavior

I could specify a screen per monitor.

Essentially I seek to decrease the time it takes to lock my computer with a custom screenshot. The currently flow is to:
 1. take screenshot
 2. blur it
 3. call i3lock

Since I have one vertical and horizontal monitor of different resolutions, I end up with black areas which wastes time. I also want to run the screenshot capture and blurring on separate threads which I can do in the following manner:

```bash
// screenshot.sh
flameshot screen -n $SCREEN -r | convert - -blur 0x6 lockscreen-$SCREEN.png
```

Then I can just this script for both my monitors in separate threads. But I now have no way to specify to i3lock which image to use for which monitor. 

I could combine the images, and use the black pixels to figure out the bottom offset for the horizontal monitor - but I wonder if that is needed. Thanks for any response.

**Comment by jcstill** [comment]
For the screen, try using `scrot`. I am able to capture a 1080p and 4K screen at the same time without surrounding the 1080 with black.I think it scales the 4K down in the image, but I'm not sure exactly how it works.

For the speed, it's ImageMagik thats taking the time. To speed it up, you could blur less or try to optimize `convert`: https://stackoverflow.com/questions/28704984/how-to-speed-up-a-complex-image-processing
