### ISSUE TITLE
Add option to remove/modify lock key text

### ISSUE THREAD

**Issue by OraBB1t** [Raymo111/i3lock-color#172]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

When a wrong password entered, by default i3lock lets the user know with a text if num lock or caps lock is on. As useful as it is some like me wants a clean, minimalist lockscreen without those texts.

## Expected Behavior

Give user an option to disable this num/caps lock text.
Something like,
` --no-lockkey-text`

**OR**

Ability to edit those texts' font, color, size, position etc.
## Reproduction Instructions

Can produce when using 'ring'
Can't produce with 'bar'

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 2.12.c.1
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[ ] Built from source yourself
[x] Other (Please describe in detail)
</pre>
Arch community repo

**Comment by Raymo111** [comment]
I'll put this in my TODO list. Sounds like a great idea and seems doable.
