### ISSUE TITLE
Lockscreen doesn't appear right away after waking the computer from sleep

### ISSUE THREAD

**Issue by ghost** [Raymo111/i3lock-color#174]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

After an update from 2.12.c.1 to 2.12.c.2, I can see my screen when the laptop wakes up from sleep. The lockscreen only appears after I begin typing my password.  

## Expected Behavior

Before the update, when the laptop was waking up from sleep, I could see the lockscreen right away

## Reproduction Instructions

- update to i3lock-color v2.12.c.2
- set `xset s off dpms 5` for the sleep function to kick in after 5 seconds of inactivity
 
## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.12.c.2 (2020-04-18) © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[ ] Built from source yourself
[x] Other (Please describe in detail)
</pre>
I modified the [Arch official PKGBUILD](https://git.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/i3lock-color) to build the commit I wanted

**Comment by Raymo111** [comment]
How are you running `i3lock` after wake?

**Comment by ghost** [comment]
in my i3 config, I have `exec --no-startup-id xss-lock -l screenlock.sh` and here is the content of screenlock.sh
```
wallpaper=$HOME/PathToWallpaper.png
i3lock --pass-media-keys --pass-screen-keys -n -t -i $wallpaper \
    --insidecolor=72bfb900 --ringcolor=000000ff --line-uses-inside \
    --keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000 \
    --insidevercolor=fecf4dff --insidewrongcolor=d23c3dff \
    --ringvercolor=ffffffff --ringwrongcolor=ffffffff --indpos="50:573"\
    --ring-width=2 \
    --radius=12 --veriftext="" --wrongtext="" --noinputtext=""
```

**Comment by Raymo111** [comment]
@zimawho try https://gist.github.com/Raymo111/91ffd256b7aca6a85e8a99d6331d3b7b instead of xss-lock.

**Comment by ghost** [comment]
I tried your systemd solution to no avail so I built every commit from 2.12.c.1 to 2.12.c.2. The bug seems to be introduced by [commit 5a7e156](https://github.com/Raymo111/i3lock-color/commit/5a7e156bfcd7d1c901dbc82f0c41b2c896f416b3) which makes little sense because it barely changed `i3lock.1` file. I am going to investigate a bit further

**Comment by Raymo111** [comment]
Have you tried using the git version from AUR? I've tried many times to get @AladW to update to the latest version (and even applied for TU status) but to no avail. The community PKGBUILD is SEVERELY out of date and I don't like that one bit :/

**Comment by ghost** [comment]
The community PKGBUILD is on latest release (2.12.c.4) so not really out of date anymore. It's an orphan package now though, so maybe you could try to apply again and maintain it. I also tried the AUR package and it has the same bug

**Comment by AladW** [comment]
Sorry for the lack of communication, I've started my MSc and I have close to 0 time for Arch stuff. Good someone else updated it, though.

**Comment by Raymo111** [comment]
@AladW I understand!

Sincerely,
Raymond Li

**Comment by Raymo111** [comment]
@zimawho unfortunately I have been told, quite angrily, that I am ineligible for TU status right now. Try building the latest version from git and seeing if the problem still exists?

**Comment by ghost** [comment]
The bug is still present after building latest version from git but not present when building i3lock from upstream ...

**Comment by Zebradil** [comment]
I have no issues with locking before my system is going to sleep, while using [i3lock-color-git from AUR](https://aur.archlinux.org/packages/i3lock-color-git) (current version is `r736.b2c1024-2`) with the following systemd service:

```systemd
[Unit]
Description=Lock screen on suspend
Before=sleep.target suspend.target hibernate.target hybrid-sleep.target

[Service]
User=%I
Environment=DISPLAY=:0
Type=forking
ExecStart=/home/%I/bin/systemd-lock
ExecStartPost=/usr/bin/sleep 1

[Install]
WantedBy=sleep.target suspend.target hibernate.target hybrid-sleep.target
```

`systemd-lock` contains only `i3lock` invocation with some theming arguments.

**Comment by darianmorat** [comment]
I couldn't find a clean solution so I just went with: xautolock

```config
# Lock screen after 9min (screen goes off after 10min)
# xautolock handles idle timeout, xss-lock handles suspend
exec --no-startup-id xautolock -time 9 -locker ~/.config/i3/lock.sh
exec --no-startup-id xss-lock --transfer-sleep-lock -- ~/.config/i3/lock.sh
```
