### ISSUE TITLE
short aguments have wrong format in the manual

### ISSUE THREAD

**Issue by Bravo555** [Raymo111/i3lock-color#177]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>

## Description
![image](https://user-images.githubusercontent.com/10912424/88117276-fc91f180-cbba-11ea-8fef-63390ad15e28.png)

The manual says that these options are provided like this: `-S=number`, `-B=sigma`.
**However the correct format is `-S number` `-B sigma`**

**Comment by Raymo111** [comment]
Fixed! Thanks for pointing this out!
