### ISSUE TITLE
PAM incompatibility between distros

### ISSUE THREAD

**Issue by Mef45** [Raymo111/i3lock-color#178]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

When I try to unlock my computer, i3lock will not accept my password, even if it is correct

## Expected Behavior

i3lock unlock computer, when typed pass is correct

## Reproduction Instructions

1. Call i3lock from somewhere (terminal, hotkey, etc)
2. Type correct password
3. Press "Enter"

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.12.c.5 © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2020 Raymond Li
OS: Debian GNU/Linux 10 (buster) x86_64
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[x] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Mef45** [comment]
If i revert `pam/i3lock` from `system-auth` back to `login`, all goes to normal

https://github.com/Raymo111/i3lock-color/commit/6b34624e74ec17e421e00d94bef956671d327e1e

**Comment by Raymo111** [comment]
aaargh shoot

**Comment by Raymo111** [comment]
@Mef45 what's your `uname -a`?

**Comment by Mef45** [comment]
> @Mef45 what's your `uname -a`?

`Linux 10-145-213-226 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux`

**Comment by Raymo111** [comment]
I see. Guess I'll have to implement a way to switch that based on OS.

**Comment by Raymo111** [comment]
@Mef45 can you see if adding any of these after the `auth include system-auth` line works?
```
auth sufficient login
auth optional login
auth include login
```

Ref: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/managing_smart_cards/pam_configuration_files#pam-control

**Comment by Mef45** [comment]
> @Mef45 can you see if adding any of these after the `auth include system-auth` line works?
> 
> ```
> auth sufficient login
> auth optional login
> auth include login
> ```

Add it to `/etc/pam.d/i3lock` or to `pam/i3lock` before rebuild?

**Comment by Raymo111** [comment]
pam/i3lock before rebuild

**Comment by Mef45** [comment]
`auth sufficient login` not work
`auth optional login` not work
`auth include login` not work

All of them in one time does not help too

**Comment by Raymo111** [comment]
@Mef45 I've reverted the commit for now, until I figure out a way to make it work.

**Comment by Raymo111** [comment]
@Mef45 can you check that it works now? Thanks!

**Comment by Mef45** [comment]
> @Mef45 can you check that it works now? Thanks!

Yep, now `/etc/pam.d/i3lock` contains both `system-auth` (commented) and `login` (uncommented) and all works fine.

Thank you.

**Comment by Raymo111** [comment]
@Mef45 can you try the latest release just to make sure? It's cause I moved the logic to the `configure.ac` file.

**Comment by Mef45** [comment]
> @Mef45 can you try the latest release just to make sure? It's cause I moved the logic to the `configure.ac` file.

latest release also works fine

**Comment by Raymo111** [comment]
Awesome. Thanks for your help then!
