### ISSUE TITLE
Rebase from upstream (2.8)

### ISSUE THREAD

**Issue by aslafy-z** [Raymo111/i3lock-color#18]
Hi,

i3lock 2.8 was released on Jun 4, 2016,
Can you rebase from upstream ?

Thank you, and good job for your work !

**Comment by PandorasFox** [comment]
https://github.com/chrjguill/i3lock-color/blob/master/CHANGELOG

I already have all the commits from 2.8. I'm actually completely up to date with upstream as of the time of writing this comment, unless their github repo is lagging behind some other remote repo I don't know of.

I do need to go revert that commit to the changelog, though. I dunno why I did that.
