### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by altair00** [Raymo111/i3lock-color#182]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

After building i3lock-color whenever I try to run './install-i3lock-color.sh' I am getting an error. It says the following:

<details><summary>Output</summary>
<pre>
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'
rm: cannot remove 'build/i3lock-randr.o': Permission denied
rm: cannot remove 'build/.deps/i3lock-i3lock.Po': Permission denied
rm: cannot remove 'build/.deps/i3lock-tinyexpr.Po': Permission denied
rm: cannot remove 'build/.deps/i3lock-dpi.Po': Permission denied
rm: cannot remove 'build/.deps/i3lock-jpg.Po': Permission denied
rm: cannot remove 'build/.deps/i3lock-blur.Po': Permission denied
rm: cannot remove 'build/.deps/i3lock-blur_simd.Po': Permission denied
rm: cannot remove 'build/.deps/i3lock-randr.Po': Permission denied
rm: cannot remove 'build/.deps/i3lock-xcb.Po': Permission denied
rm: cannot remove 'build/.deps/i3lock-unlock_indicator.Po': Permission denied
rm: cannot remove 'build/i3lock': Permission denied
rm: cannot remove 'build/stamp-h1': Permission denied
rm: cannot remove 'build/config.status': Permission denied
rm: cannot remove 'build/i3lock-jpg.o': Permission denied
rm: cannot remove 'build/config.log': Permission denied
rm: cannot remove 'build/i3lock-unlock_indicator.o': Permission denied
rm: cannot remove 'build/i3lock-blur_simd.o': Permission denied
rm: cannot remove 'build/i3lock-i3lock.o': Permission denied
rm: cannot remove 'build/i3lock-xcb.o': Permission denied
rm: cannot remove 'build/Makefile': Permission denied
rm: cannot remove 'build/i3lock-tinyexpr.o': Permission denied
rm: cannot remove 'build/config.h': Permission denied
rm: cannot remove 'build/i3lock-blur.o': Permission denied
rm: cannot remove 'build/i3lock-dpi.o': Permission denied
../configure: line 1993: config.log: Permission denied
../configure: line 2003: config.log: Permission denied
/bin/bash ./config.status --recheck
running CONFIG_SHELL=/bin/bash /bin/bash ../configure --prefix=/usr --sysconfdir=/etc --no-create --no-recursion
../configure: line 1993: config.log: Permission denied
../configure: line 2003: config.log: Permission denied
make: *** [Makefile:486: config.status] Error 1
make: *** No rule to make target 'install'.  Stop.
install: cannot stat '../LICENSE': No such file or directory
</pre>
</details>

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 2.12.c.5-3-g9a1793d
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[x] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by altair00** [comment]
By the way the 'LICENSE' file is in the same directory.

**Comment by Raymo111** [comment]
If you're installing it, you don't need to build it first. Remove the `build` subdirectory, and just run `./install-i3lock-color.sh`.

**Comment by altair00** [comment]
I removed the build subdirectory and run **./install-i3lock-color.sh** but the problem persists.

**Comment by Raymo111** [comment]
Hmm... Can you post the output of:
```
pwd && ls -lah && rm -rf build && ls -lah && ./install-i3lock-color.sh
```
please?

**Comment by altair00** [comment]
<details><summary>Output</summary>
<pre>
/home/cassie/Downloads/i3lock-color
total 1.1M
drwxrwxr-x 9 cassie cassie 4.0K Oct  9 23:53 .
drwxr-xr-x 4 cassie cassie 4.0K Oct  9 23:52 ..
-rw-rw-r-- 1 cassie cassie  55K Oct  9 23:52 aclocal.m4
-rwxr-xr-x 1 cassie cassie 5.7K Oct  9 23:53 ar-lib
drwxr-xr-x 2 cassie cassie 4.0K Oct  9 23:53 autom4te.cache
-rw-rw-r-- 1 cassie cassie 5.7K Oct  9 23:52 blur.c
-rw-rw-r-- 1 cassie cassie  428 Oct  9 23:52 blur.h
-rw-rw-r-- 1 cassie cassie 3.3K Oct  9 23:52 blur_simd.c
drwxrwxr-x 3 cassie cassie 4.0K Oct  9 23:53 build
-rwxrwxr-x 1 cassie cassie  190 Oct  9 23:52 build.sh
-rw-rw-r-- 1 cassie cassie 7.5K Oct  9 23:52 CHANGELOG
-rw-rw-r-- 1 cassie cassie  330 Oct  9 23:52 .clang-format
-rwxr-xr-x 1 cassie cassie 7.3K Oct  9 23:53 compile
-rwxr-xr-x 1 cassie cassie  44K Oct  9 23:53 config.guess
-rw-rw-r-- 1 cassie cassie 6.0K Oct  9 23:52 config.h.in
-rwxr-xr-x 1 cassie cassie  36K Oct  9 23:53 config.sub
-rwxrwxr-x 1 cassie cassie 307K Oct  9 23:52 configure
-rw-rw-r-- 1 cassie cassie 6.5K Oct  9 23:52 configure.ac
-rw-rw-r-- 1 cassie cassie  109 Oct  9 23:52 cursors.h
-rwxr-xr-x 1 cassie cassie  24K Oct  9 23:53 depcomp
-rw-rw-r-- 1 cassie cassie 2.9K Oct  9 23:52 dpi.c
-rw-rw-r-- 1 cassie cassie  556 Oct  9 23:52 dpi.h
-rw-rw-r-- 1 cassie cassie  425 Oct  9 23:52 fonts.h
drwxrwxr-x 8 cassie cassie 4.0K Oct  9 23:52 .git
drwxrwxr-x 3 cassie cassie 4.0K Oct  9 23:52 .github
-rw-rw-r-- 1 cassie cassie  587 Oct  9 23:52 .gitignore
-rw-rw-r-- 1 cassie cassie  15K Oct  9 23:52 i3lock.1
-rw-rw-r-- 1 cassie cassie  78K Oct  9 23:52 i3lock.c
-rw-rw-r-- 1 cassie cassie  762 Oct  9 23:52 i3lock.h
-rw-rw-r-- 1 cassie cassie    9 Oct  9 23:52 I3LOCK_VERSION
-rwxrwxr-x 1 cassie cassie  117 Oct  9 23:52 install-i3lock-color.sh
-rwxr-xr-x 1 cassie cassie  16K Oct  9 23:53 install-sh
-rw-rw-r-- 1 cassie cassie 3.5K Oct  9 23:52 jpg.c
-rw-rw-r-- 1 cassie cassie  482 Oct  9 23:52 jpg.h
-rw-rw-r-- 1 cassie cassie 1.6K Oct  9 23:52 LICENSE
-rwxrwxr-x 1 cassie cassie  767 Oct  9 23:52 lock_bar.sh
-rwxrwxr-x 1 cassie cassie  878 Oct  9 23:52 lock.sh
drwxrwxr-x 2 cassie cassie 4.0K Oct  9 23:52 m4
-rw-rw-r-- 1 cassie cassie 1.1K Oct  9 23:52 Makefile.am
-rw-rw-r-- 1 cassie cassie  49K Oct  9 23:53 Makefile.in
-rwxr-xr-x 1 cassie cassie 6.8K Oct  9 23:53 missing
drwxrwxr-x 2 cassie cassie 4.0K Oct  9 23:52 pam
-rw-rw-r-- 1 cassie cassie 8.8K Oct  9 23:52 randr.c
-rw-rw-r-- 1 cassie cassie  294 Oct  9 23:52 randr.h
-rw-rw-r-- 1 cassie cassie 6.5K Oct  9 23:52 README.md
-rw-rw-r-- 1 cassie cassie  429 Oct  9 23:52 rgba.h
-rw-rw-r-- 1 cassie cassie 123K Oct  9 23:52 screenshot.png
-rwxrwxr-x 1 cassie cassie  21K Oct  9 23:52 tinyexpr.c
-rw-rw-r-- 1 cassie cassie 2.3K Oct  9 23:52 tinyexpr.h
drwxrwxr-x 2 cassie cassie 4.0K Oct  9 23:52 travis
-rw-rw-r-- 1 cassie cassie  691 Oct  9 23:52 .travis.yml
-rw-rw-r-- 1 cassie cassie  45K Oct  9 23:52 unlock_indicator.c
-rw-rw-r-- 1 cassie cassie 1.7K Oct  9 23:52 unlock_indicator.h
-rw-rw-r-- 1 cassie cassie  20K Oct  9 23:52 xcb.c
-rw-rw-r-- 1 cassie cassie 1.9K Oct  9 23:52 xcb.h
total 1.1M
drwxrwxr-x 8 cassie cassie 4.0K Oct 10 00:01 .
drwxr-xr-x 4 cassie cassie 4.0K Oct  9 23:52 ..
-rw-rw-r-- 1 cassie cassie  55K Oct  9 23:52 aclocal.m4
-rwxr-xr-x 1 cassie cassie 5.7K Oct  9 23:53 ar-lib
drwxr-xr-x 2 cassie cassie 4.0K Oct  9 23:53 autom4te.cache
-rw-rw-r-- 1 cassie cassie 5.7K Oct  9 23:52 blur.c
-rw-rw-r-- 1 cassie cassie  428 Oct  9 23:52 blur.h
-rw-rw-r-- 1 cassie cassie 3.3K Oct  9 23:52 blur_simd.c
-rwxrwxr-x 1 cassie cassie  190 Oct  9 23:52 build.sh
-rw-rw-r-- 1 cassie cassie 7.5K Oct  9 23:52 CHANGELOG
-rw-rw-r-- 1 cassie cassie  330 Oct  9 23:52 .clang-format
-rwxr-xr-x 1 cassie cassie 7.3K Oct  9 23:53 compile
-rwxr-xr-x 1 cassie cassie  44K Oct  9 23:53 config.guess
-rw-rw-r-- 1 cassie cassie 6.0K Oct  9 23:52 config.h.in
-rwxr-xr-x 1 cassie cassie  36K Oct  9 23:53 config.sub
-rwxrwxr-x 1 cassie cassie 307K Oct  9 23:52 configure
-rw-rw-r-- 1 cassie cassie 6.5K Oct  9 23:52 configure.ac
-rw-rw-r-- 1 cassie cassie  109 Oct  9 23:52 cursors.h
-rwxr-xr-x 1 cassie cassie  24K Oct  9 23:53 depcomp
-rw-rw-r-- 1 cassie cassie 2.9K Oct  9 23:52 dpi.c
-rw-rw-r-- 1 cassie cassie  556 Oct  9 23:52 dpi.h
-rw-rw-r-- 1 cassie cassie  425 Oct  9 23:52 fonts.h
drwxrwxr-x 8 cassie cassie 4.0K Oct  9 23:52 .git
drwxrwxr-x 3 cassie cassie 4.0K Oct  9 23:52 .github
-rw-rw-r-- 1 cassie cassie  587 Oct  9 23:52 .gitignore
-rw-rw-r-- 1 cassie cassie  15K Oct  9 23:52 i3lock.1
-rw-rw-r-- 1 cassie cassie  78K Oct  9 23:52 i3lock.c
-rw-rw-r-- 1 cassie cassie  762 Oct  9 23:52 i3lock.h
-rw-rw-r-- 1 cassie cassie    9 Oct  9 23:52 I3LOCK_VERSION
-rwxrwxr-x 1 cassie cassie  117 Oct  9 23:52 install-i3lock-color.sh
-rwxr-xr-x 1 cassie cassie  16K Oct  9 23:53 install-sh
-rw-rw-r-- 1 cassie cassie 3.5K Oct  9 23:52 jpg.c
-rw-rw-r-- 1 cassie cassie  482 Oct  9 23:52 jpg.h
-rw-rw-r-- 1 cassie cassie 1.6K Oct  9 23:52 LICENSE
-rwxrwxr-x 1 cassie cassie  767 Oct  9 23:52 lock_bar.sh
-rwxrwxr-x 1 cassie cassie  878 Oct  9 23:52 lock.sh
drwxrwxr-x 2 cassie cassie 4.0K Oct  9 23:52 m4
-rw-rw-r-- 1 cassie cassie 1.1K Oct  9 23:52 Makefile.am
-rw-rw-r-- 1 cassie cassie  49K Oct  9 23:53 Makefile.in
-rwxr-xr-x 1 cassie cassie 6.8K Oct  9 23:53 missing
drwxrwxr-x 2 cassie cassie 4.0K Oct  9 23:52 pam
-rw-rw-r-- 1 cassie cassie 8.8K Oct  9 23:52 randr.c
-rw-rw-r-- 1 cassie cassie  294 Oct  9 23:52 randr.h
-rw-rw-r-- 1 cassie cassie 6.5K Oct  9 23:52 README.md
-rw-rw-r-- 1 cassie cassie  429 Oct  9 23:52 rgba.h
-rw-rw-r-- 1 cassie cassie 123K Oct  9 23:52 screenshot.png
-rwxrwxr-x 1 cassie cassie  21K Oct  9 23:52 tinyexpr.c
-rw-rw-r-- 1 cassie cassie 2.3K Oct  9 23:52 tinyexpr.h
drwxrwxr-x 2 cassie cassie 4.0K Oct  9 23:52 travis
-rw-rw-r-- 1 cassie cassie  691 Oct  9 23:52 .travis.yml
-rw-rw-r-- 1 cassie cassie  45K Oct  9 23:52 unlock_indicator.c
-rw-rw-r-- 1 cassie cassie 1.7K Oct  9 23:52 unlock_indicator.h
-rw-rw-r-- 1 cassie cassie  20K Oct  9 23:52 xcb.c
-rw-rw-r-- 1 cassie cassie 1.9K Oct  9 23:52 xcb.h
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'
mkdir: created directory 'build/'
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for gsed... sed
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for gawk... (cached) gawk
checking for GNU make... make
checking for a sed that does not truncate output... /usr/bin/sed
checking whether to build with code coverage support... no
checking whether to enable debugging... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for mode_t... yes
checking for off_t... yes
checking for pid_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for pid_t... (cached) yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking whether lstat correctly handles trailing slash... yes
checking for working strnlen... yes
checking for atexit... yes
checking for dup2... yes
checking for ftruncate... yes
checking for getcwd... yes
checking for gettimeofday... yes
checking for localtime_r... yes
checking for memchr... yes
checking for memset... yes
checking for mkdir... yes
checking for rmdir... yes
checking for setlocale... yes
checking for socket... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strncasecmp... yes
checking for strndup... yes
checking for strrchr... yes
checking for strspn... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoul... yes
checking for explicit_bzero... yes
checking for library containing floor... -lm
checking for library containing ev_run... -lev
checking for library containing shm_open... -lrt
checking for library containing pam_authenticate... -lpam
checking for library containing iconv_open... none required
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for XCB... yes
checking for XCB_IMAGE... yes
checking for XCB_UTIL... yes
checking for XCB_UTIL_XRM... yes
checking for XKBCOMMON... yes
checking for CAIRO... yes
checking for JPEG... yes
checking for FONTCONFIG... yes
checking for gawk... (cached) gawk
checking how to run the C preprocessor... gcc -E
checking whether make sets $(MAKE)... (cached) yes
checking for ranlib... ranlib
checking whether ln -s works... yes
checking for ar... ar
checking the archiver (ar) interface... ar
checking CFLAGS for maximum warnings... -Wall
checking whether C compiler accepts -Wunused-value... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking paths.h usability... yes
checking paths.h presence... yes
checking for paths.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking whether C compiler accepts -fsanitize=address... yes
checking whether the linker accepts -fsanitize=address... yes
checking whether C compiler accepts -fno-omit-frame-pointer... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: executing buildir commands
config.status: skipping top_srcdir/Makefile - not created
config.status: executing depfiles commands
--------------------------------------------------------------------------------
build configured:

  i3lock version:         2.12.c.5-3-g9a1793d (2020-09-13)
  is release version:     no

  enable debug flags:     yes
  code coverage:          no
  enabled sanitizers:     address 

To compile, run:
  cd /home/cassie/Downloads/i3lock-color/build && make
\--------------------------------------------------------------------------------
make  all-am
make[1]: Entering directory '/home/cassie/Downloads/i3lock-color/build'
  CC       i3lock-blur.o
  CC       i3lock-blur_simd.o
  CC       i3lock-dpi.o
  CC       i3lock-jpg.o
  CC       i3lock-i3lock.o
  CC       i3lock-randr.o
  CC       i3lock-tinyexpr.o
  CC       i3lock-unlock_indicator.o
  CC       i3lock-xcb.o
  CCLD     i3lock
make[1]: Leaving directory '/home/cassie/Downloads/i3lock-color/build'
[sudo] password for cassie: 
make: *** No rule to make target 'install'.  Stop.
install: cannot stat '../LICENSE': No such file or directory
</pre>
</details>

here it is

**Comment by Raymo111** [comment]
This is a bug. Thanks for the issue!

**Comment by Raymo111** [comment]
@Altair-POD can you pull the latest version and check if it works?

**Comment by altair00** [comment]
It is working brother..... 

Jazak Allahu Khairan

**Comment by Raymo111** [comment]
Awesome. Can't believe that went uncaught for 2 months lol. I'm gonna close this now, if anything comes up feel free to make a new issue (or reply here if it's the same issue).
