### ISSUE TITLE
Element width/height in --*pos for better alignment?

### ISSUE THREAD

**Issue by basenc** [Raymo111/i3lock-color#189]
version aur-1127e2a (2020-10-28)
![noname](https://user-images.githubusercontent.com/26507468/101967075-5ad37580-3c2b-11eb-9f02-ea2536eef2c8.png)

**Comment by Raymo111** [comment]
Can you clarify what you mean? Please follow the issue template if you can, thanks!

**Comment by basenc** [comment]
I'm sorry.
Existing --pos expression system doesnt allow you to position time/date/layout blocks by using their width and height variables, which can vary depending on font family and time size you use. Because of that, you are forced to adjust their position pixel perfect which both isn't looks very nice and also breaks all your configuration up if you try to adjust something, or just switch monitor resolution.

![image](https://user-images.githubusercontent.com/26507468/101970445-76df1300-3c3b-11eb-90af-44da1e98e740.png)
![image](https://user-images.githubusercontent.com/26507468/101970450-7f374e00-3c3b-11eb-8266-05a5bcbfafbc.png)

For example, on pic related i'm trying to place my password indicator and time string on the bottom left corner of the screen, which is pretty easy for the password circle:
`--indpos = "15 + r:h - 15 - r"`
but not for the clock:
`--timepos = "ix + r + 10:965"`
I have to use the exact pre-calculated Y position to align the center of indicator with the center of clock, so it wont look so odd and mispositioned. The element height variable `th` should solve this issue:
`--timepos = "ix + r + 10:iy + r - th / 2"`
![noname2](https://user-images.githubusercontent.com/26507468/101971571-4dc28080-3c43-11eb-869e-1e9aa7725558.png)

And it should work even if i change font or decide to make time indicator bigger

**Comment by Raymo111** [comment]
Sorry, I'm not quite understanding. What is `th` supposed to be?

**Comment by basenc** [comment]
> Sorry, I'm not quite understanding. What is `th` supposed to be?

Pixel height of the time widget/block, or, to be exactly, calculated font height. Would be nice to have this for layout indicator too.

**Comment by Raymo111** [comment]
Thing is, now there's time, date, layout, ring/bar, and a bunch of other variables, multiplied by 2 (th and tw). Plus, how would that even be calculated?

I don't think this is something that can be implemented, and there really isn't any point, as it's easier to calculate it yourself once than to have a bunch of variables that never get used.
