### ISSUE TITLE
Empty image, --raw 0x0 and -c 000000ff not having a fully black background

### ISSUE THREAD

**Issue by tosti007** [Raymo111/i3lock-color#190]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior
When using an empty image file `background.png` or an empty string and using options `--raw "0x0:rgb" -c '000000ff'` the screen is not fully black, but rather really dark but still transparent. 

However, if using `-c ff0000ff` the screen is fully red, which also works for any other combination of rgb as long as any of it's components (r, g, or b) if has max value (`ff`). If any of the components is a value lower than `ff` (e.g. `-c fe0000ff`) then the color is transparent.

## Expected Behavior
I would expect to see a fully black background.

## Reproduction Instructions
First create an empty image with the command below or use `echo ""` instead of `cat background.png` in the following steps.
```bash
$ touch background.png
```

This gives expected behavior, but gives an error message:
```bash
$ i3lock --image background.png -c 000000ff
Error searching for JPEG header in background.png
```

This too gives expected behavior, but also an error message:
```bash
$ cat background.png | i3lock --image /dev/stdin --raw "0x0" -c 000000ff
Invalid image format: "0x0"
```

This gives the expected behavior with no output:
```bash
$ cat background.png | i3lock --image /dev/stdin --raw "0x0:rgb" -c ffffffff
```

This gives the behavior described in `Current Behavior` with no output:
```bash
$ cat background.png | i3lock --image /dev/stdin --raw "0x0:rgb" -c 000000ff
```

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.12.c.5 © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2020 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (aur/i3lock-color 2.12.c.5-1 (+5 2.69))
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

## Edits
1. Tested for other colors than white and it turns out that any combination other than full white with any component being `ff` also has transparency.
2. Added that echo-ing an empty string also works.

**Comment by Raymo111** [comment]
So the option for image only allows a JPEG (or PNG?). Simply using an empty file or `"0x0"` will result in an invalid image format.
