### ISSUE TITLE
i3lock-color has been removed from Arch Linux community repo

### ISSUE THREAD

**Issue by jian-lin** [Raymo111/i3lock-color#192]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>

Unfortunately, i3lock-color has been removed from Arch Linux community repo. As a result, the link ( [Stable version in Community](https://www.archlinux.org/packages/community/x86_64/i3lock-color/) )  in the readme is broken.

**Comment by Raymo111** [comment]
What happened was the original maintainer left, the package was then orphaned, and then it got demoted to AUR during routine housecleaning. I'm the current maintainer on AUR, and I'm looking at getting a TU to sponsor it back into Community.

**Comment by jian-lin** [comment]
I see. Thanks. Feel free to close this issue.
