### ISSUE TITLE
package available on Gentoo Linux

### ISSUE THREAD

**Issue by jian-lin** [Raymo111/i3lock-color#193]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>

Hi there.

i3lock-color has been packaged on [GURU](https://wiki.gentoo.org/wiki/Project:GURU) repo, which is an official repo of Gentoo Linux. I think adding this information to the readme may help Gentoo users.

Thanks for your work. Feel free to close this issue.

**Comment by Raymo111** [comment]
Can you link the specific package for me? Thanks.

**Comment by jian-lin** [comment]
The package is called `x11-misc/i3lock-color` and can be found at the mirror of GURU on [github](https://github.com/gentoo/guru).

**Comment by Raymo111** [comment]
Thanks!

**Comment by jian-lin** [comment]
It seems like you make a mistake in the last commit.

**Comment by Raymo111** [comment]
Can you be more specific?
Edit: Oh nvm I see. Thanks.
