### ISSUE TITLE
FcCacheFini: Assertion `fcCacheChains[i] == NULL' failed.

### ISSUE THREAD

**Issue by minhducsun2002** [Raymo111/i3lock-color#195]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior
Lockscreen randomly (as in, I have no reliable method to trigger the error) crashes after launched, leaving what's behind it exposed.
Launching via terminal repeatedly yields this when it crashed :
```
i3lock: fccache.c:807: FcCacheFini: Assertion `fcCacheChains[i] == NULL' failed.
```

## Expected Behavior
It doesn't crash anymore.

## Reproduction Instructions
Just launch i3lock with whatever valid options you want. It happens randomly, so the bug might not even appear at all on some machines.

## Environment
Output of `i3lock --version`:
<pre>
$ i3lock --version
i3lock: version 2.13.c.1 © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2020 Raymond Li 
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (i3lock-color)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

[fontconfig issue 227](https://gitlab.freedesktop.org/fontconfig/fontconfig/-/issues/227) seems to be related to this.
For reference, here's my fontconfig installation :
```
$ yay -Qi fontconfig
Name            : fontconfig
Version         : 2:2.13.91+48+gfcb0420-2
```

**Comment by Raymo111** [comment]
`fccache.c` isn't a file in i3lock-color, and that assertion isn't in the code either, so unfortunately I'm unable to help. Good luck fixing it though!

**Comment by minhducsun2002** [comment]
Oh, it looks like this problem comes from upstream. Sorry!

**Comment by Raymo111** [comment]
Not necessarily upstream, perhaps external. No worries though 🙃
