### ISSUE TITLE
Regression from i3lock : display of capslock status when wrong password is typed

### ISSUE THREAD

**Issue by bmateu** [Raymo111/i3lock-color#199]
## This issue is a....

<pre>
[ ] Bug
[x] Feature request
</pre>

# Description

When a wrong password is typed native i3lock displays in the lock ring "Caps lock" or "num lock" if those modifiers are enabled. This is very useful on keyboard that do not have capslock/numlock status led. 

A similar feature would be nice in this fork, e.g. by adding `--wrongtextcapslock="text"` options.

**Comment by Raymo111** [comment]
I thought we had that option by default? I recently merged a PR to provide the option of disabling it, were you looking for something different?
