### ISSUE TITLE
Petition for name change

### ISSUE THREAD

**Issue by krey** [Raymo111/i3lock-color#200]
First of all - thank you for developing and maintaining this great project.

I think i3lock-color needs to either get merged into i3 or get a better name.

i3lock has a bunch of missing features that i3lock-color provides, and color is just one of them.

I switched for keyboard layout indication:
https://github.com/i3/i3lock/issues/294
https://github.com/i3/i3lock/issues/287
https://github.com/i3/i3lock/issues/116
https://github.com/i3/i3lock/issues/100
https://github.com/i3/i3lock/issues/82
https://github.com/i3/i3lock/issues/56

Some name ideas off the top of my head
i3-screenlock, i3lock-plus, lock-i3-up

**Comment by Nathan13888** [comment]
Cool suggestion, but I think there is no need for a name change. i3lock-color is meant to be a **super set** of i3lock so this name is suitable and accurately describes the purpose of this project. In addition, a name change would make the project unrecognizable for users of this project. It is also impractical for such a change as it means that the name of the binary would have to be changed as well as in everyone's configs.

**Comment by Nathan13888** [comment]
**No need** *

**Comment by Raymo111** [comment]
@krey I think that at this point a whole lotta people know what `i3lock-color` is, and changing the name would be like changing `mkp224o` to `oniongenerator`, some names just stick and I don't think `i3lock-color` should be changed.
