### ISSUE TITLE
Use system-local-login instead of system-auth for PAM

### ISSUE THREAD

**Issue by msafadieh** [Raymo111/i3lock-color#201]
## This issue is a....

<pre>
[ ] Bug
[ X ] 3rd party configuration error
</pre>

## Current Behavior

i3lock currently uses `include system-auth` for PAM by default on Arch & Gentoo.

## Expected Behavior

i3lock should use `system-local-login` instead as it's meant for local logins.

## Reproduction Instructions

I currently use `pam_u2f.so` to get passwordless login with a hardware token. I restrict this functionality to local logins by configuring `system-local-login`. I cannot configure `system-auth` as it is also inherited by `system-remote-login` which affects stuff like SSH. i3lock ignores my passwordless configuration as it instead checks `system-auth` instead of `system-local-login`.

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.13.c.1 © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2020 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[ X ] AUR package (i3lock-color)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by msafadieh** [comment]
Also, I can confirm `system-local-login` is included in the `pambase` package for both [Gentoo](https://github.com/gentoo/pambase) and [Arch](https://archlinux.org/packages/core/any/pambase/files/).

**Comment by Raymo111** [comment]
What login method does fprint use? I'm hesitant to switch to `system-local-auth` because I can find literally no info about it, and PAM is such a sensitive area of the project that I don't wanna make rash decisions on it.

**Comment by msafadieh** [comment]
fprint should use `system-local-login` according to the [Arch Wiki](https://wiki.archlinux.org/index.php/fprint#Login_configuration) and is also what [GDM](https://github.com/GNOME/gdm/blob/fb319044165f2b4c6e194cf26380c29efc675f64/data/pam-arch/gdm-fingerprint.pam) is using. The [Gentoo wiki article](https://wiki.gentoo.org/wiki/Pam_u2f#Configuring_PAM) on FIDO U2F also suggests using `system-local-login` for configuring local logins.

Ultimately, `system-local-login` includes `system-login` which includes `system-auth`. So any top-level configuration to `system-auth` should still work.

`/etc/pam.d/system-local-login`:
```
#%PAM-1.0

auth      include   system-login
account   include   system-login
password  include   system-login
session   include   system-login
```

`/etc/pam.d/system-login`:
```
#%PAM-1.0

auth       required   pam_shells.so
auth       requisite  pam_nologin.so
auth       include    system-auth

account    required   pam_access.so
account    required   pam_nologin.so
account    include    system-auth

password   include    system-auth

session    optional   pam_loginuid.so
session    optional   pam_keyinit.so       force revoke
session    include    system-auth
session    optional   pam_motd.so          motd=/etc/motd
session    optional   pam_mail.so          dir=/var/spool/mail standard quiet
-session   optional   pam_systemd.so
session    required   pam_env.so           user_readenv=1
```

**Comment by Raymo111** [comment]
Got it. Looks good.
