### ISSUE TITLE
[REQUEST] Set actual width of bar indicator

### ISSUE THREAD

**Issue by Barbaross93** [Raymo111/i3lock-color#205]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

Currently, when specifying with the `--bar-position` option, the bar can only be affected in terms of offset depending on its orientation. It always spans across the entire screen.

## Expected Behavior

 Ideally, the actual width (not the `--bar-base-width` option) should be adjustable in addition to the bar indicator's offset

## Reproduction Instructions

When trying to use `--bar-position=...` setting anything with the `w` parameter causes it to exit and state `Failed to reason about 'w:h/2-100' given by '--bar-position'`

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: i3lock: version 2.13.c.2 (2021-02-15) © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2020 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (which one?) (git)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
@Rio6 can you take a look?

**Comment by Rio6** [comment]
Yeah I think it makes sense to have a `--bar-position` to replace `--bar-offset`. Yet another deprecated option about bars :P

**Comment by Raymo111** [comment]
Can you make it work then :)

**Comment by Rio6** [comment]
Yeah I'm looking at it right now, just not sure what to do with the old params. Make them backward compatible or just ignore them all together.

**Comment by Raymo111** [comment]
Great. If you can make the backward compatible it would be great; if you can't then fprintf a warning message saying this option is now deprecated. Whatever you do don't reuse the options.

**Comment by Rio6** [comment]
Just realized it's already called `--bar-position` XD, it's called offset in other places.

I'll try to extend on the original one while keeping compatibility then.

**Comment by Raymo111** [comment]
Awesome, thanks!

**Comment by Rio6** [comment]
I really want to use `--bar-width` :P ~~It's been deprecated for 2 days anyways.~~

What else can I use? `--bar-total-width` might be a good one. @Raymo111 thoughts?

**Comment by Barbaross93** [comment]
Maybe `--bar-screen-width`?

**Comment by Raymo111** [comment]
@Rio6 it's just that we don't wanna reuse options that people might have in their config scripts and do different things. What do you want the new `--bar-width` to do?

**Comment by Rio6** [comment]
Yeah I get that, that's why I'm looking for other parameter names. This new param is used to set the total width of the bar. The old bar-width was used to set the width of the indivisual mini bars, which got deprecated by bar-count.

I like --bar-total-width peronally.

**Comment by Raymo111** [comment]
Ahh I see. It makes sense now. I like `bar-total-width` as well, let's go with that then.
