### ISSUE TITLE
Clock in wrong position on multi monitor setup

### ISSUE THREAD

**Issue by gavsiu** [Raymo111/i3lock-color#207]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

25" 2560x1440 external monitor connected to 15" 1920x1080 laptop. External monitor set as primary. Laptop lock screen clock is not in correct position.

## Expected Behavior

Both monitors should have the clock on the bottom left corner. Only the external primary monitor has it set correctly. My old 17" laptop did not have this issue. I don't remember the resolution on it. Sounds similar to [this](https://github.com/Raymo111/i3lock-color/issues/26).

## Reproduction Instructions

15" Laptop set to 1920x1080
25" Monitor set to 2560x1440 and set as primary display connected through USB C to DisplayPort
Using Intel/Nvidia drivers. No bumblee (I use prime-run).
Bspwm. No DE.

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: version 2.13.c.2
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (which one?)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>
i3lock-color

**Comment by Raymo111** [comment]
Can you send screenshots and provide the specific command you used? Also, which AUR version did you install, git or non-git?

**Comment by gavsiu** [comment]
![2021-02-22-112339_4480x1618_scrot](https://user-images.githubusercontent.com/806613/108767031-bc0ca480-750a-11eb-91ba-ee09f23f8121.png)

<details>
<summary>
Script used to run i3lock-color
</summary>
<pre>
#!/usr/bin/env bash
#
# i3lock-lock

# Pause dunst before locking to hide notifications
pkill -u $USER -USR1 dunst

# Background shape for time/date
rectangles=" "

SR=$(xrandr --query | grep ' connected' | grep -o '[0-9][0-9]*x[0-9][0-9]*[^ ]*')
for RES in $SR; do
  SRA=(${RES//[x+]/ })
  CX=$((${SRA[2]} + 40))
  CY=$((${SRA[1]} - 40))
  rectangles+="rectangle $CX,$CY $((CX+405)),$((CY-90)) "
done

# Import colors from .Xresources
source $HOME/.Xresources.d/colors.sh
transparent=#00000000

# Font
font="Iosevka"

# Pixelated screenshot as background
TMPBG=/tmp/screen.png
scrot $TMPBG
convert $TMPBG -scale 10% -scale 1000% -draw "fill ${bg1} fill-opacity 0.8 $rectangles" $TMPBG

# Lock screen
i3lock \
    --image $TMPBG \
    --nofork \
    --ignore-empty-password \
    --indicator \
    --force-clock \
    \
    --insidevercolor=${color[4]}FF \
    --ringvercolor=${color[4]}FF \
    --verifcolor=$transparent \
    \
    --insidewrongcolor=${color[1]}FF \
    --ringwrongcolor=${color[1]}FF \
    --wrongcolor=$transparent \
    \
    --insidecolor=$transparent \
    --ringcolor=${fg1}FF \
    --line-uses-inside \
    --layoutcolor=$transparent \
    \
    --keyhlcolor=${color[2]}FF \
    --bshlcolor=${color[1]}FF \
    --separatorcolor=$transparent \
    \
    --timecolor=${fg1}FF \
    --datecolor=${fg1}FF \
    \
    --timestr="%r" \
    --datestr="%A, %d %B %Y" \
    \
    --indpos="x+400:h-84" \
    --timepos="x+55:h-88" \
    \
    --time-align=1 \
    --date-align=1 \
    \
    --time-font=$font \
    --date-font=$font \
    \
    --timesize=32 \
    --datesize=22 \
    \
    --veriftext="" \
    --wrongtext="" \
    --noinputtext="" \
    --locktext="" \
    --lockfailedtext="" \
    \
    --radius=28 \
    --ring-width=9.0

# Delete screenshot
rm $TMPBG

# Resume dunst notifications
pkill -u $USER -USR2 dunst
</pre>
</details>

[i3lock-color](https://aur.archlinux.org/packages/i3lock-color/)

My lock script hasn't really changed since it worked on my old laptop. Old laptop was connected through DisplayPort to Mini DisplayPort.

**Comment by Raymo111** [comment]
I see that you used `--indpos="x+400:h-84" --timepos="x+55:h-88"`, perhaps that only works for your monitor on the right?

**Comment by gavsiu** [comment]
Laptop:
![2021-02-22-131507_1920x1080_scrot](https://user-images.githubusercontent.com/806613/108771182-270caa00-7510-11eb-9b76-9e580cfbbdf5.png)

Monitor:
![2021-02-22-131537_2560x1440_scrot](https://user-images.githubusercontent.com/806613/108771205-2ffd7b80-7510-11eb-80b8-ef3229980d62.png)

Same script, just turned off each screen. It was fine on my old laptop with the same monitor and same script.

**Comment by Rio6** [comment]
@gavsiu Have you tried using `y + h - 88` as the y position?

**Comment by gavsiu** [comment]
> @gavsiu Have you tried using `y + h - 88` as the y position?

Thank you. That fixed it.
