### ISSUE TITLE
[Request] Modifier text options?

### ISSUE THREAD

**Issue by Barbaross93** [Raymo111/i3lock-color#208]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

Perhaps I'm somehow missing it, but there doesn't seem to be an option to change the size of the modifier text (among other parameters). There are options for the outline of the modifier, but not it's size, position, font, etc

## Expected Behavior

There should be options specifically for the modifier since there are complete options for everything else.

## Reproduction Instructions

1) Read the man page
2) Notice lack of options for modifier text
3) Try doing `--modifiersize` `--nodifierfont` anyway because it might be undocumented
4) Lock fails to start
5) Ask about modifier options on github

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: i3lock: version aur-085df46 (2021-02-18) © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2020 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (which one?) Git
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
I believe it's implemented... I think as `modsize`? Can you try that? If it works I'll update the manpage and make `modifieroutline` `modoutline`.

**Comment by Barbaross93** [comment]
Indeed, it is `--modsize`! Turns out position is `--modifpos` for position as well. I can't figure out what it is for font though. Maybe they should all be `modif`? There's `--modif-align` that's documented.

**Comment by Raymo111** [comment]
Yikes I hate non-standard implementation. Ok I'll standardize all of these and update the man page soon.

**Comment by Raymo111** [comment]
Ok I finally got around to standardizing the args. I'll look into adding tab-completion soon as well. I'm standardizing EVERYTHING, so a lot of people's scripts will break but I think it'll worth it for the future.

**Comment by Raymo111** [comment]
Ok, that's been fixed. I'll push this out as 2.13.c.3 soon.

**Comment by souravdas142** [comment]
@Raymo111 `--modif-color` is not implemented yet?

**Comment by souravdas142** [comment]
@Raymo111  nevermind giving a PR for --modif-color .
