### ISSUE TITLE
Text colour doesn't change

### ISSUE THREAD

**Issue by YarnSphere** [Raymo111/i3lock-color#21]
Since a recent update, the text colour option `--textcolor` doesn't seem to be working.
I am always getting the text in black no matter what argument I pass.

**Comment by PandorasFox** [comment]
I might've screwed up a merge commit. I'll investigate.

**Comment by PandorasFox** [comment]
Stuff is definitely broken. I should have a fix within an hour or so.

Sorry about that - I knew that that merge commit probably wasn't great, and that I'd likely screwed up something. There's also something affecting the "verifying" background color, as well.

**Comment by PandorasFox** [comment]
Alright!

Sorry about that - I ended up having a couple regressions from the really big merge. A couple `||`'s got dropped, and I dropped a couple other lines.

I should've reviewed that merge commit more / not done it so early - lemme know if stuff is fixed now.

**Comment by YarnSphere** [comment]
Sorry for the delay; seems fixed!
Thank you for your work!
