### ISSUE TITLE
[Dunst] System Notifications are shown on active lockscreen

### ISSUE THREAD

**Issue by leahoswald** [Raymo111/i3lock-color#210]
## This issue is a....
<pre>
[X] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior
If I lock my screen notifications from firefox (e.g Slack) are still shown on the lock screen. This can lead to a leak of private data.

## Expected Behavior
Notifications of all kind are hidden.

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: i3lock: version 2.13.c.2
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (which one?) aur/i3lock-color 2.13.c.2-1
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
You should configure whatever notification system you use to not display them when you run i3lock-color (easiest way is using a script). This isn't something that i3lock-color will actively prevent, because some people may want to see notifs over the lockscreen.

**Comment by ouuan** [comment]
There's a solution for the original i3lock: https://github.com/i3/i3lock/issues/22#issuecomment-290543752

I tried it for both i3lock and i3lock-color, but it works for i3lock only.

**Comment by ouuan** [comment]
> There's a solution for the original i3lock: [i3#22 (comment)](https://github.com/i3/i3lock/issues/22#issuecomment-290543752)
> 
> I tried it for both i3lock and i3lock-color, but it works for i3lock only.

I used `git bisect` and found that 0da5cdb4479da47109eea9530ae941ebf11462fa is the first bad commit.

**Comment by ouuan** [comment]
I used git bisect and found that 0da5cdb is the first bad commit (i.e. #152). So we should be able to fix this.

**Comment by Raymo111** [comment]
@ouuan you have any idea why that commit broke your notification hiding?

**Comment by ouuan** [comment]
> @ouuan you have any idea why that commit broke your notification hiding?

I'm not familiar with the i3lock codes nor xcb development, so I have no idea. There are some PRs mentioned in i3#22. I don't know if they are useful.

If you want to test, it's simple:

1. `dunst &`
2. `i3lock & sleep 1 && notify-send test`

**Comment by ouuan** [comment]
If this won't get fixed, a patch/fork to revert #152 will also be very helpful, since I don't use the alpha channel feature. I tried to revert it but failed to resolve the conflicts.

**Comment by parisni** [comment]
having the same issue. So far, no way to disable notify-send by itself

**Comment by parisni** [comment]
finally found a workaround @ouuan @Raymo111 :  kill dunst and resume it after locking. This way the notification are disabled during the locking

```
#!/bin/sh
killall -SIGUSR1 dunst # pause

# Run i3lock no-fork
i3lock -n 

# resume message display
killall -SIGUSR2 dunst # resume

```

**Comment by ouuan** [comment]
> finally found a workaround @ouuan @Raymo111 : kill dunst and resume it after locking. This way the notification are disabled during the locking

You don't need to kill dunst. You can use `dunstctl set-paused`.

This does not completely fix the problem because it works only for dunst and not for other notifications.
