### ISSUE TITLE
Clarify curly brace behavior in manpage

### ISSUE THREAD

**Issue by Swarthe** [Raymo111/i3lock-color#217]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

As per the manpage:
> --{layout, time, date, greeter}-color=rrggbbaa

However, when we run i3lock with this argument in `sh`, it fails:
![1](https://user-images.githubusercontent.com/70660340/120029691-ba191c80-bff6-11eb-8a5f-bab6cd1cef4a.png)

When we modify the command to remove the spaces within the braces, it functions as expected:
![2](https://user-images.githubusercontent.com/70660340/120029963-2267fe00-bff7-11eb-9b25-7582172b0b96.png)

## Expected Behavior

This argument (and others with the same format) should function with spaces as described in the manpage.

## Reproduction Instructions

Simply run `i3lock --{time, date}-color=999999` or something similar in `sh`.

## Environment
Output of `i3lock --version`: 
<pre>
i3lock: version 2.13.c.3 © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2021 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (i3lock-color)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
You can only use one option at a time. So try `i3lock-color --time-color=ffffff --date-color=ffffff`.

**Comment by Swarthe** [comment]
`i3lock --{time,date}-color=999999` does work as expected though, which seems to have been the source of my confusion. My apologies.

**Comment by Raymo111** [comment]
I think that's bash globbing things? I don't think there's i3lock-color code handling that. Not quite sure lol.

**Comment by Swarthe** [comment]
It is apparently a [feature](https://www.gnu.org/software/bash/manual/html_node/Brace-Expansion.html) of bash. Should the difference be clarified in the manpage?

**Comment by Raymo111** [comment]
Some people might be using a different shell, but I think it would be good to make a note in the manage, yes.

**Comment by Swarthe** [comment]
i3lock is usually executed from a script, so I think it would affect almost everyone. I believe this brace behavior is present in most shells anyway. Would the addition of simple examples suffice?

**Comment by Raymo111** [comment]
Most people know not to take curly braces literally. There's no need for examples, a simple notice under the first place in the manpage where this is used will suffice. Also not all shells support this behaviour.

**Comment by Swarthe** [comment]
Very well. I will make a PR soon.
