### ISSUE TITLE
Example screenshot would really "sell" it

### ISSUE THREAD

**Issue by kootenpv** [Raymo111/i3lock-color#22]
I'm curious how the example colors you wrote down looks like. A screenshot example would be nice.

Note that it's not exactly clear how to install it (not without yaourt for example), so I'd need the extra motivation :-)

It seems very useful though.

**Comment by PandorasFox** [comment]
I'm currently in the middle of exams / grading exams / moving out of my dorm, so I'll do that next month when my desktop is set up again.

**Comment by ghost** [comment]
@kootenpv meskarune has an example which is using this i3lock-color https://github.com/meskarune/i3lock-fancy

**Comment by PandorasFox** [comment]
f14f5b1459366221ea2304c3696a533c79f8c636 :3
