### ISSUE TITLE
Feature-Request: Unlock-Hook

### ISSUE THREAD

**Issue by SebTM** [Raymo111/i3lock-color#225]
## This issue is a....
<pre>
[ ] Bug
[X] Other kind of issue (Please describe in detail)
</pre>

## Topic
We currently implementing stopping/resuming notifications while locked and I wanted to ask if there are some better ways to check/hook into unlock. (https://github.com/pavanjadhaw/betterlockscreen/issues/219)

If not, would it be an option to implement something like unlock-Hook in the future?

**Comment by Raymo111** [comment]
Can you just have a check for the PID of the `i3lock` process? Since there should only be the instance that betterlockscreen launches and no other i3lock processes right? So the hook can just be when i3lock exits? (Which it does when the screen is unlocked.)

**Comment by Rio6** [comment]
Another alternative is to start i3lock with `--nofork` option and run command after it finishes.

**Comment by souravdas142** [comment]
> Another alternative is to start i3lock with --nofork option and run command after it finishes.

yeah @Rio6, This is more logical I think instead of https://github.com/Raymo111/i3lock-color/issues/225#issuecomment-853510848 ? I already implemented https://github.com/Raymo111/i3lock-color/issues/225#issuecomment-853510848 see https://github.com/pavanjadhaw/betterlockscreen/pull/233/commits/64eea99093103d7b10bfe1221727aa9985126e02 (something like `busy wait`) wouldn't it consumes lot of cpu resources @Raymo111 ? difference between with or without `--nofork` ?

**Comment by bew** [comment]
Busy wait will use cpu for nothing, it's not really efficient..

Instead if you want to start the locker, and wait for it to end before doing something else you can use `--nofork`:
```sh
# do before lock hook stuff here

i3lock ..... --nofork
# the script will block until the screen is unlocked and i3lock returns

# do unlock hook stuff here
```

Another way is to use the shell to put i3lock in the background, save the pid, do other things and finally wait efficiently for i3lock to exit:
```sh
# do before lock hook stuff here

i3lock ..... --nofork &
# Using `--nofork` and `&` ensures the PID we get with `$!` is the process of the locker, not of a bootstrap process (like the default)
SAVED_PID=$!

# now i3lock is still running in the background, we can do other things...

# to wait for i3lock to exit efficiently, use:
wait "$SAVED_PID"

# do unlock hook stuff here
```

**Comment by Raymo111** [comment]
@souravdas142 fork means i3lock-color will run in the background, and anything in the script after the i3lock command will be run immediately after the lockscreen starts. No fork means any command in the script after i3lock will run after i3lock exits, once the screen is unlocked.

**Comment by souravdas142** [comment]
Thank you @Raymo111 now there is no confusion.

**Comment by souravdas142** [comment]
Thank you @bew Tested all from https://github.com/Raymo111/i3lock-color/issues/225#issuecomment-853783169 , both have the same effect but later version enables you to do other things while i3lock-color runs in background. Now which version is better in terms of cpu consumptions or efficency? @SebTM  @bew

**Comment by SebTM** [comment]
I don't see a real need for running forking per default in Betterlockscreen, so if no one has concerns I would go with running Betterlockscreen non-forking per default (we would need to adjust systemd-service again) and rename postLock to postUnlock.

The only thing which came to my mind was: Do we need a postLock function somehow like executing something after i3lock-color launched? And from the current cases we have/had I don't see the need.

So thanks @Raymo111 @bew @souravdas142 for the Feedback and Help!
