### ISSUE TITLE
Syntax unrecognized

### ISSUE THREAD

**Issue by Kritiqual** [Raymo111/i3lock-color#236]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

I made a simple script to test out i3lock, but when i appied `--refresh-rate 0.1` and re-run the script, it's shown:
```
i3lock: unrecognized option '--refesh-rate'
i3lock: Syntax: i3lock [-v] [-n] [-b] [-d] [-c color] [-u] [-p win|default] [-i image.png] [-t] [-e] [-f]
Please see the manpage for a full list of arguments.
```

## Expected Behavior

Show the i3lock screen

## Reproduction Instructions

In the script i added this:
```
[...]
--refresh-rate 0.1 \
```

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: version 2.13.c.4 © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2021 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (i3lock-color)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
The `--refresh-rate` option, like all other long-form options (starting with `--`), must be specified with an equal sign (`--refresh-rate=0.1`).

**Comment by JezerM** [comment]
Long-form options doesn't need to be specified with `=`.  The problem might be here:
```
i3lock: unrecognized option '--refesh-rate'
```
Change `--refesh-rate` to `--refresh-rate` :D

**Comment by Raymo111** [comment]
Huh interesting, apparently I can't read. Thanks @JezerM.

**Comment by Kritiqual** [comment]
oh, my typo, now the real issue is sometime I cannot unlock when input correct password after input wrong password
