### ISSUE TITLE
Image slideshow

### ISSUE THREAD

**Issue by Qwerty-Space** [Raymo111/i3lock-color#240]
## This issue is a....

- [ ] Bug
- [x] Other kind of issue (Please describe in detail)

How do I make an image slideshow?  I've seen the options in the man page, but I'm not sure how to pass multiple images.  Or does it just update the initial image passed if it's changed?

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 2.13.c.4
</pre>

Where'd you get i3lock-color from?

- [x] AUR package (which one?)
- [ ] Built from source yourself
- [ ] Other (Please describe in detail)

**Comment by JezerM** [comment]
Use the `--image [path_to_dir]` flag with the directory where your images belong to (instead of an image).

Then, use `--slideshow-interval` and `--slideshow-random-selection` to set the change interval and whether the images are selected randomly, respectively.

Like:
```sh
i3lock --image ~/Images/ --slideshow-interval 5
```

**Comment by Qwerty-Space** [comment]
Thanks @JezerM 

Can I instead link to an image, and use slideshow-interval to re-load that same image?

**Comment by JezerM** [comment]
Nop, I think it's not possible. All images are loaded and saved within i3lock, so you can't change the image and expect it to change in i3lock after it's been loaded.

**Comment by Qwerty-Space** [comment]
> Nop, I think it's not possible. All images are loaded and saved within i3lock, so you can't change the image and expect it to change in i3lock after it's been loaded.

But isn't that essentially what the slideshow is doing?  It's loading a new image.  So if it loaded a "new" image from the same path, wouldn't that be basically the same thing?

**Comment by JezerM** [comment]
Well, ideally that's how it should be, but this would load the image every time the slideshow is going to change (which might lead to performance problems).

The slideshow system in i3lock-color reads the directory you passed in, loads all the images and saves them statically; this happens only when i3lock is run, so whatever change you do to the directory or the images are not updated in i3lock.

So, i3lock loads the images and that's it, no updates. Then, after some time, the image is changed based on all the saved images.

**Comment by Qwerty-Space** [comment]
That sounds like it'll cause performance problems too.  What if the folder has thousands of images?

It should load at most 5 images into RAM, then when the next image transition occurs discard the old one, and load the new one

**Comment by JezerM** [comment]
There is a limit of 255 images, so all the performance problems are subject to the user. If they want to load 255 8K images... it's their problem.

So even if you have a folder of thousands of images, only 255 will be loaded.

If this seems a problem, just create another folder with the images you require.

**Comment by JezerM** [comment]
> It should load at most 5 images into RAM, then when the next image transition occurs discard the old one, and load the new one

Doing this is the same as loading one image every time an update is made, but with a delay of 4 images. Therefore, the performance problem is still there.

**Comment by Qwerty-Space** [comment]
I'm sorry, I really don't get how loading a single image every few minutes will cause more performance issues than loading several images at once on lock.

I'll close this issue now

**Comment by JezerM** [comment]
Hmm, you have a point there. If there's a difference of minutes, it maybe better to not load the images at once... Now I have my doubts.

**Comment by Qwerty-Space** [comment]
I can open a new issue regarding this if you like.  I think I've opened your eyes up to something here ;-)

**Comment by 9ary** [comment]
@Qwerty-Space asked my opinion so: even if the slideshow interval is only a few seconds, the time it takes to load a single image from the filesystem isn't really much of an issue. If you want to avoid extra delay each time, you can always preload the next image asynchronously, but preloading everything at startup is a waste of time and memory.

**Comment by JezerM** [comment]
Yeah, I had some problems with images, so my thought was to not load them at "runtime". Sorry for that, you can make another issue :D
This could be changed.

**Comment by Qwerty-Space** [comment]
Done :-)
