### ISSUE TITLE
[Feature request] Enable video file playing (via mpv, mplayer, gstreamer or similar)

### ISSUE THREAD

**Issue by wakatara** [Raymo111/i3lock-color#244]
## This issue is a....

<pre>
[ ] Bug
[X] Other kind of issue (Feature request!)
</pre>

## Current Behavior

When i3lock-color locks it goes to an image or color - it would be amazing if it could also play video files while locked (in particular, I am trying to emulate the effect of the [Aerial screensaver](https://aerialscreensaver.github.io/) or SDDM's Display Manager's Aerial theme (which in itself emulates the Aerial screensaver for OSX - which takes it's videos from AppleTV... =] ). 

## Expected Behavior

You lock the screen and a super cool video file plays until (or even during) you typing in your password to unlock. 

## Reproduction Instructions

n/a

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 2.13
</pre>

Where'd you get i3lock-color from?

<pre>
[X] AUR package (i3lock-color-git)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by JezerM** [comment]
As far as I know, using programs like **mpv** inside **i3lock** could make things chunky, maybe laggy, and with unexpected behavior; just playing mpv in front of i3lock won't allow you to see i3lock... or things like that. So, perhaps an integrated video player within **i3lock** (no external program) could be the solution, if this is even going to be done~

**Comment by wakatara** [comment]
@JezerM 

Sorry, I should have been clearer... I did not mean by using the aplpication outright. I imagine an interface exists to play from i3lock-color through one of those mechanisms (for example, in SDDM, it uses photon and gstreamer to accomplish the video playing. 

Unfortunately, I know little about X11 internals in this regard (though would be willing to learn and help out, cause it seems like fun, cool superpowers to add to the lock screen capabilities.).  =]

**Comment by Raymo111** [comment]
Like what JezerM said, this feature will make things too clunky. I don't know of any lockscreens that play video. Besides, you can do
```
i3lock -c 00000000 & mpv '/path/to/video.mp4' --fullscreen
```
to play fullscreen video with the screen locked.

**Comment by wakatara** [comment]
@Raymo111 
I have to admit I had not thought of this, so thank you, but I'm assuming that with the unlock that happens the video still plays after you unlock here. I was looking for a more integrated experience, but will try this out on my linux laptop as soon as I'm back from travelling. 

And, just for the record, the https://github.com/3ximus/aerial-sddm-theme implements a similar functionality in the SDDM login manager, which is pretty much what I am trying to get to under sway or i3-gaps (and what plays in my macbook air when I lock the screen - it's a seriously nice effect tbh... :-) ).

Just since I'm slightly ignorant of i3 internals, is the issue with i3lock implementing this the cairo libraries, or... ? (tbh, I'm using sway, so it's more my interest in possibly implementing something from scratch as a nice entrée project in Rust or such to teach myself... ). 

thanks (and merry Xmas if you celebrate!).

**Comment by Raymo111** [comment]
So if you want it to stop playing you can tack on `&& pkill mpv` to that command, or use a more friendly mpv command for that if there is one (in case you have other mpv videos paused/playing), you'll have to look at the mpv docs for that.

The reason I don't really want to include video playing is i3lock-color is supposed to be a simple lightweight _screen locker_, so tacking on things like video playing, widgets, control over what can display over it, etc just makes it a lot bulkier than needed. Plus, the more features the more bugs, and you really don't want bugs in the program that keeps your computer locked 🙂

I do celebrate, Merry Christmas to you too 🌲
