### ISSUE TITLE
pam_fprintd.so  and --ignore-empty-password stuck at validation

### ISSUE THREAD

**Issue by kidpixo** [Raymo111/i3lock-color#245]
## This issue is a....

<pre>
[ X ] Bug (??I'm not sure??)
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

**WARNINIG** Maybe I misunderstand what `--ignore-empty-password` does, in this case sorry and close this issue! Or maybe this option interferes with PAM fingerptint validation?

Using [ArchWiki](https://wiki.archlinux.org/title/Fprint#Login_configuration) fprint configruation in `/etc/pam.d/system-local-login`:
```
/etc/pam.d/system-local-login

auth      sufficient pam_fprintd.so
auth      include   system-login
...
```
i3lock-color with option `-e, --ignore-empty-password` doesn't unlock, but keep stuck on `Validating...`.

I must switch tty, edit `pam_fprintd.so` out of `/etc/pam.d/system-local-login` and kill i3lock-color to procede.

## Expected Behavior

`i3lock-color --ignore-empty-password` unlock with fingerprint following [ArchWiki](https://wiki.archlinux.org/title/Fprint#Login_configuration) fprint configruation (see above).

## Reproduction Instructions
- set up fprint like in [ArchWiki](https://wiki.archlinux.org/title/Fprint#Login_configuration) 
- `i3lock-color --ignore-empty-password` 
- try to unlock

## Environment
OS: Arch
Output of `i3lock --version`:
<pre>
i3lock: version 2.13.c.4 © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2021 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[X] AUR package https://aur.archlinux.org/packages/i3lock-color/
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
`--ignore-empty-password` basically prevents a PAM auth attempt when no characters have been typed. I think that might be interfering with your fprint integration (technically i3lock-color doesn't support fprint even though I know a lot of people use them together) so that option probably stops it from working?

**Comment by kidpixo** [comment]
Hi, thanks for the quick answer!
I think you are right, to unlock with i3lock-color (and i3lock) the user must 1. press enter and then 2. touch the fingerprint reader.
I think `--ignore-empty-password` makes i3lock-color skip the step 1. and waits for a characters.

I just changed my lock script to call i3lock-color without this option, I open the issue to document the behavior for future users.
