### ISSUE TITLE
Dim feature request

### ISSUE THREAD

**Issue by Anonymous78910** [Raymo111/i3lock-color#246]
## This issue is a....

<pre>
[ ] Bug
[* ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior
Blurred lock without any dim

## Expected Behavior
Adding the dim background feature will help text to be more readable

**Comment by Raymo111** [comment]
Correct me if I'm wrong, but I believe you can use a background color (with alpha) to dim over blur?

**Comment by Anonymous78910** [comment]
Gotcha. Thanks
