### ISSUE TITLE
Layout text doesn't disappear when verifying

### ISSUE THREAD

**Issue by SafwanLjd** [Raymo111/i3lock-color#249]
[ ] Bug
[x] Other kind of issue (Please describe in detail)

## Current Behavior
When you enter a password and wait for verification, the date and time text disappear to leave space for the verification text; however, the layout text does not

Picture: 
![picture](https://user-images.githubusercontent.com/59485214/147105414-c28b4a81-90ef-4225-b6d2-6e6b8edabca5.png)

## Expected Behavior

The layout text should disappear with the date and time text, or at lease there should be an option to achieve this.

## Output of `i3lock --version:`

`i3lock: version 2.13.c.4`

[x] AUR package (aur/i3lock-color)
[ ] Built from source yourself
[ ] Other (Please describe in detail)

**Comment by Raymo111** [comment]
The other `text`s also don't disappear. This behavior is intentional, only date and time are hidden during verification because of an update lag issue.
