### ISSUE TITLE
Keyboard not being recaptured after passing special keys with `--special-passthrough`

### ISSUE THREAD

**Issue by SafwanLjd** [Raymo111/i3lock-color#252]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

slightly after using one of the "special keys" (i.e. the volume keys), you get the ability to pass any key, if you use the shortcut keys to launch another program that requests the focus, like a terminal, you'll be able to run commands, i.e. `pkill i3lock`

## Expected Behavior

This shouldn't happen

## Reproduction Instructions

Here is a demonstration where I'm using sxhkd to bind "Super + Enter" to launch Alacritty
![screenrecord](https://user-images.githubusercontent.com/59485214/152347108-48099686-194a-4f16-8937-668f87832d12.gif)

## Environment
Output of `i3lock --version`:
`i3lock: version aur-ac6b471 (2022-01-25)`

Where'd you get i3lock-color from?

<pre>
[x] AUR package (i3lock-color-git)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by JezerM** [comment]
Certainly, I was expecting something related to `--special-passtrough`, but not like this. It's weird that i3lock doesn't regain its keyboard control... I'll have to check it.

**Comment by JezerM** [comment]
Does this happens only with volume keys? Or brightness and media keys too?

**Comment by SafwanLjd** [comment]
> 

It happens with all the "special" keys, I just used the volume keys as an example

**Comment by JezerM** [comment]
Also, does this only happens with `sxhkd`? Have you tested other Window Managers/Desktop Environments where this issue occurs?

**Comment by SafwanLjd** [comment]
I haven't, since that's the only environment I use... but `sxhkd` is the most popular stand-alone hotkey daemon, so it'd be a big deal even if it's just that

**Comment by JezerM** [comment]
I can confirm this happens with `sxhkd` and dwm.

**Comment by Raymo111** [comment]
Oh dear. @SafwanLjd thanks for reporting this, @JezerM please fix this as soon as you can, I'm gonna wait until that happens to release a new version.

**Comment by JezerM** [comment]
For now, this feature had to be reverted.

**Comment by Raymo111** [comment]
Feat reverted due to the same vuln being present on KDE (and this probably everywhere the flag is used).
