### ISSUE TITLE
Wrong password handler

### ISSUE THREAD

**Issue by Naheel-Azawy** [Raymo111/i3lock-color#254]
## This issue is a....

<pre>
[ ] Bug
[X] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

This feature does not exist, I guess.

## Expected Behavior

This is a feature request. It would be nice if we can have an option to invoke commands when wrong passwords are entered.
Maybe we can have something like:
```sh
i3lock --on-wrong-password='echo WRONG $p' # where $p is the entered password
```
Or maybe easier and nicer
```sh
i3lock --wrong-password-to-stdout | while read event p; do
    if [ "$event" = 'wrong-password' ]; then # maybe other events can be added later if needed?
        echo WRONG $p
    fi
done
```

## Why?
This can be useful in many ways, at least to me. For example, 
- if a wrong password is entered the camera takes a picture and sends it by email or sends an sms warning
- maybe if wrong passwords are entered for, say 3 times, we lockdown the computer, unmount encrypted drives, etc...
- use special passwords to perform whatever magic action
- maybe switch users as well

Overall, I think this has a lot of potential and should be fairly easy to implement. What do you think?

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.13.c.4 © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2021 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[X] AUR package (which one?)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
Can't PAM be configured to do this instead of i3lock-color?

**Comment by Naheel-Azawy** [comment]
Hi, sorry it took me a while to get back.
Well, honestly I'm not sure. I know that PAM exists but I haven't tried messing around with it before. Any hints?
If it can be done easily straight from PAM configs maybe we can close this and I better read my man pages I guess.

**Comment by Raymo111** [comment]
@Naheel-Azawy quick Google shows:
* https://bbs.archlinux.org/viewtopic.php?id=220506
* https://unix.stackexchange.com/questions/348038/how-to-correctly-use-pam-to-execute-a-script-upon-login-failure

Closing this for now.

**Comment by Naheel-Azawy** [comment]
Thank you @Raymo111 and sorry for the noise

**Comment by Raymo111** [comment]
No worries 🙂
