### ISSUE TITLE
Floating windows can appear over the lockscreen if they signal a change

### ISSUE THREAD

**Issue by Dareka826** [Raymo111/i3lock-color#255]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>

I don't think this is a bug, but a feature request? I'm really not sure how to categorize this. (I've tested several prior versions of i3lock-color and all of them showed this behavior)

## Additional information
I am using `dwm` as my window manager. I am unsure whether this happens just on `dwm` or on other window managers/desktop environments as well.

## Current Behavior
Whenever there's a floating window and it signals a change (like changing title or sending the bell character) it gets raised above `i3lock`. It is not interactable, but its contents are visible.

## Expected Behavior
A window shouldn't be able to raise above the lockscreen. I tested this scenario with `slock` as well, but it didn't let the window raise above it.

## Reproduction Instructions
1. Open a terminal
2. Make it a floating window
3. Input `sleep 3 && printf "\a"`
4. Lock the screen before the 3 seconds pass
5. The window should appear over the lockscreen after sleep exits

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version aur-380a10a (2022-02-03) © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2021 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (i3lock-color-git)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
Doesn't seem to be an issue for me on KWin. Might be a DWM issue similar to notifications... in general these types of issues are `wontfix` because they're wm-dependent. That being said you're welcome to submit a PR for it!
