### ISSUE TITLE
image sometimes doesn't show up until first keyboard input after display wake

### ISSUE THREAD

**Issue by devsnek** [Raymo111/i3lock-color#257]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior
sometimes when the screen wakes, the image is not shown and whatever was on my screen when i locked the computer is visible(!!). the background and lock circle don't show up until a key is pressed.

## Expected Behavior
the image should always be shown

## Reproduction Instructions

i don't have a consistent repro but it only happens when waking the screen.

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.13.c.4 © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2021 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (which one?) https://aur.archlinux.org/packages/i3lock-color
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
I can't repro this either. I'm gonna close this as an issue specific to your setup, you can reopen it if you can provide steps to consistently repro it.
