### ISSUE TITLE
Clock broken in multi monitor setups

### ISSUE THREAD

**Issue by ghost** [Raymo111/i3lock-color#26]
Whatever was done in e64f9adedcd34d54272399a64c93888ad70cc346 doesn't work well with multi monitor setups.

I have two external monitors connected to my notebook via a docking station, only one of which displays the clock in the right position.

The second monitor doesn't show the clock at all. The build-in notebook monitors shows the clock in the wrong position, apparently at the same coordinates as the primary monitor although the built-in monitor is much smaller.

Furthermore, the clock doesn't go away anymore when validating passwords which leads to texts being rendered on top of each other and therefore being unreadable.

**Comment by PandorasFox** [comment]
hnnnnng. I had a hunch there were problems with dual monitors, but I'm without my desktop until I move into my place on friday.

I'm going to go see about digging out one of my monitors and testing stuff.

**Comment by PandorasFox** [comment]
Alright; I just fixed a few strings and fixed the clock/indicator text. If there's text being rendered inside the indicator, then the clock won't render at all for now.

(I may change it in the future so that this can be overridden [`--always-show-clock`, maybe.]; indicator text can already be hidden effectively by simply setting it to have an alpha channel of 0.)

I'll see if I can like... emulate a 2nd display or something so that I can test the clock on it. 

> I have two external monitors connected to my notebook via a docking station, only one of which displays the clock in the right position.
>
> The second monitor doesn't show the clock at all. The build-in notebook monitors shows the clock in the wrong position, apparently at the same coordinates as the primary monitor although the built-in monitor is much smaller.

What are the exact arguments you're giving it? I'd like to poke around at this some.

I'm assuming that you wish to have both an indicator, and the clock, on all your monitors?

**Comment by ghost** [comment]
Don't worry. I'm on a Dell notebook, with a docking station, with an Intel chipset, with "Hanns.G" monitors. I'm used to multi monitor features breaking all the time.

I'm using [this custom wrapper script](https://gist.github.com/bassch/7c5426faf6684d07ac33badd38c1d184) which analyzes the "brightness" of the given background image and then uses either a "bright" or a "dark" color set as appropriate.

Indicator and clock used to work on all monitors and it would make sense if it just continued to do so but I wouldn't mind having either of the two work on a single monitor only as long as I get to choose which one.

It's just eye candy after all.

**Comment by PandorasFox** [comment]
Alright, I see the bug with the tinyexpression stuff, I think.

I'll tinker around with it and should have a fix out by the end of the day. I'll probably make a release as 2.9.1 or something.

**Comment by PandorasFox** [comment]
Alright, I believe that I've fixed it with 3637d7ba28bf9f037f4fbfe609d1faeb2c80e521. There was some bad logic for initializing the vars. I believe it should work fine now :D

**Comment by PandorasFox** [comment]
@Jereviendrai: I changed some defaults with 245c6706c633ff44694f7bcc256aefe9b2d596fa and 3637d7ba28bf9f037f4fbfe609d1faeb2c80e521; you may want to give them a glance.

**Comment by ghost** [comment]
Seems to work now.
