### ISSUE TITLE
Passing --color 00000000 creates a black lock screen

### ISSUE THREAD

**Issue by i13e** [Raymo111/i3lock-color#260]
## This issue is a....
```
[x] Bug
[ ] Other kind of issue (Please describe in detail)
```

## Current Behavior
After a system update i3lock no longer sets a transparent background when called with the parameter `--color 00000000` (Apparently it doesn't seem to be doing transparency at all, at least for me)

## Expected Behavior
Before the update i3lock rendered the background transparent when called with that parameter

## Reproduction Instructions
1. Install i3lock-color from the AUR on Arch Linux
2. Run `i3lock --color 00000000`
3. Get a black lockscreen

## Environment
Output of `i3lock --version`:
```
i3lock: version 2.13.c.4 © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2021 Raymond Li
```

Where'd you get i3lock-color from?
```
[x] AUR package (3lock-color)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
```

## Notes
Love i3lock-color and I really appreciate you putting your time into developing this, I'm unsure if this is just an isolated incident where something on my computer is screwing it up, or is reproducible and an updated dependency screwed up the app. Let me know if there is any way that I can help!

**Comment by Raymo111** [comment]
I can't seem to reproduce this. Might there be an issue with your compositor? Which one are you using?

**Comment by i13e** [comment]
I use picom and I'm pretty sure I just fixed the problem (some line in my picom config screwed everything up). Regardless, thanks for taking the time to look at this.
