### ISSUE TITLE
i3bar shown after opening the lid of the laptop

### ISSUE THREAD

**Issue by reggermont** [Raymo111/i3lock-color#264]
**Before starting:** I didn't pushed the tests recently by lack of time, but I will in the following days. My guess is either this bug happens after a network change, either after a very long time suspended, or a triggered applet

## This issue is a....

<pre>
[X] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

i3bar is sometimes shown after lid opened, surely after unsuspend (cf [arch documentation](https://wiki.archlinux.org/title/Power_management#ACPI_events:~:text=hibernate-,HandleLidSwitch,suspend,-HandleLidSwitchDocked))
![image](https://user-images.githubusercontent.com/14902909/180193733-3ffee275-c74b-4287-b47e-3f43ef9d8aa3.png)

## Expected Behavior

i3bar not shown

## Reproduction Instructions

- Start from a fresh arch and install i3lock-color
- Use the config provided below
- Close the lid of the laptop
- Re-open it 

## Environment

Up-to-date standard arch linux, 

Output of `i3lock --version`:
<pre>
i3lock version: `i3lock: version 2.13.c.4 © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2021 Raymond Li`
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (which one?) i3lock-color
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

## i3lock configuration

Mostly inspired by the example provided, with some tweaks

```sh
BLANK='#00000000'
BLACK='#000000'
CLEAR='#ffffff22'
DEFAULT='#00ff00'
TEXT='#00ff00'
WRONG='#880000bb'
VERIFYING='#bb00bbbb'

i3lock \
    --insidever-color=$CLEAR \
    --ringver-color=$VERIFYING \
    \
    --insidewrong-color=$CLEAR \
    --ringwrong-color=$WRONG \
    \
    --inside-color=$BLANK \
    --ring-color=$DEFAULT \
    --line-color=$BLANK \
    --separator-color=$DEFAULT \
    \
    --verif-color=$TEXT \
    --wrong-color=$TEXT \
    --time-color=$TEXT \
    --date-color=$TEXT \
    --layout-color=$TEXT \
    --keyhl-color=$WRONG \
    --bshl-color=$WRONG \
    \
    --time-str="%H:%M:%S" \
    --time-size=48 \
    --timeoutline-color=$BLACK \
    --timeoutline-width=1 \
    --date-str="%A, %Y-%m-%d" \
    --date-size=22 \
    --dateoutline-color=$BLACK \
    --dateoutline-width=0.4 \
    \
    --noinput-text="No input" \
    --wrong-text="[REDACTED]" \
    \
    --screen 1 \
    --clock \
    --indicator \
    --radius 150 \
    --ring-width 12 \
    --image=[REDACTED]/Images/reggermont.png \
    --centered \
    --color=$BLANK
```

**Comment by Raymo111** [comment]
i3lock-color isn't responsible for other apps like notifications and status bars displaying over it, you'll have to ensure that they don't yourself.

**Comment by reggermont** [comment]
Should have mention it, but I was using the original i3lock for several months before and I never had this issue.

I hear your point, but looking at this, it looks like a regression

**Comment by Raymo111** [comment]
@reggermont is this happening consistently with i3lock-color? If so try switching back to i3lock and see if it's happening still.

**Comment by reggermont** [comment]
Not consistently. As I said in the description:
> My guess is either this bug happens after a network change, either after a very long time suspended, or a triggered applet

Will try to switch back to i3lock, thanks for the advice

**Comment by ironhak** [comment]
This should be fixed.
