### ISSUE TITLE
Failed to compile with lto

### ISSUE THREAD

**Issue by PetrusZ** [Raymo111/i3lock-color#266]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior
Failed to compile with lto, CFLAGS=-flto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing.

Error: ../../i3lock-color-2.13.c.4/unlock_indicator.c:119:13: error: type of �-Werror=lto-type-mismatch][]]

Full build log: https://860849.bugs.gentoo.org/attachment.cgi?id=794144

## Expected Behavior
Compile success.

## Reproduction Instructions
This bug is orignal reported on https://bugs.gentoo.org/860849.

Compile from source with CFLAGS=-flto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing to reproduce the issue.

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 2.13.c.4
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[ ] Built from source yourself
[x] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
@PetrusZ just fixed it, thanks for spotting this issue. Change will be included in the next release (2.13.c.5)
