### ISSUE TITLE
man page description for --composite is unclear

### ISSUE THREAD

**Issue by ByteDrummer** [Raymo111/i3lock-color#269]
## This issue is a....

<pre>
[ ] Bug
[x ] Other kind of issue (Please describe in detail)
</pre>

## Description
The summary of the `--composite` flag on the man page is unclear: "Some compositors have problems with i3lock trying to render over them, so this argument is disabled by default. However, some will work properly with it, so it's been left enabled." Those two sentences seem contradictory. Is the argument enabled or disabled by default, and what does it do?

**Comment by Raymo111** [comment]
It's disabled by default, but left in so that you can enable it if you'd like.

**Comment by ByteDrummer** [comment]
Ok. While using `xss-lock` to trigger locking on idle, I've found that I need to use this flag. Otherwise, the lock screen won't be drawn until I move my mouse or press a key, even while `picom` is not running. What exactly is this flag doing?

**Comment by Raymo111** [comment]
https://github.com/Raymo111/i3lock-color/blob/e565e207faf35f07e303e9da8e5da521c1f8040b/xcb.c#L161-L183 This block of code runs if the flag is provided. Basically in order to cover composited windows the composite-overlay window has to be used instead of the root window (in normal cases).

**Comment by ByteDrummer** [comment]
Thanks for the info!
