### ISSUE TITLE
Lag for Random Image Change, Occasional Freeze/Lag during Computer Lockscreen

### ISSUE THREAD

**Issue by ribbybbir** [Raymo111/i3lock-color#270]
## This issue is a....

<pre>
[x ] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

I do get some lag, skipping second counts when it is time to change random images. I also allow the monitor to sleep so it won't burn up the screen pixels.

Occasionally, I get a slow down in wake operation from monitor sleep. The lockscreen would also slow down, rendering the lock to a halt or freeze. It's basically like a lock gone rusty.

I first suspect that I am abusing the random image change too much (no, it's not in sequential order). However, I also suspect possible lag with login attempts, both in failure and success. Maybe, somebody has been building up the lag? Then again, the sleep mode of the monitor can add pressure to the lag and freeze.

Can someone test and verify such issues? I don't want to return to my computer just to find a occasional freeze/lag. It's enough that I myself might actively overload computer operations on a machine. Maybe 5 seconds before random image change is considered a potential lag problem? Maybe I should just stick to a static image or just color?

## Expected Behavior

I suppose that lag should not appear for every login attempt. I expect the lockscreen to not freeze/lag during its operation despite monitor sleep mode or short random image change intervals. Of course, a overload of programs is a user problem, something beyond the i3lock-color.

## Reproduction Instructions

Allow monitor sleep mode.
sh -c "sudo pm-suspend; i3lock --nofork --no-unlock-indicator --image='/set/user/directory/directory_of_image/' --color=000000FF --centered --clock --force-clock --layout-color=FF55FFFF --time-color=FF55FFFF --date-color=FF55FFFF --greeter-color=FF55FFFF --greeter-text='Greeter text line' --no-modkey-text --time-font='Nimbus Mono PS Regular' --date-font='Nimbus Mono PS Regular' --layout-font='Nimbus Mono PS Regular' --greeter-font='Nimbus Mono PS Regular' --date-size=30 --greeter-size=60 --greeter-pos='x--650:y--175' --slideshow-interval=5 --slideshow-random-selection"
During computer lockscreen operation, try login attempt failure and success to see lag in second count skip.
During computer lockscreen operation, leave the operation alone for a few hours at the least. You should encounter a freeze/lag on the lockscreen. I am not sure if unauthorized users are brute forcing during my absence from the computer, but it is a possibility. Still, I want to check in on the technical aspects.

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: i3lock: version 2.13.c.4-34-gd846e7c (2022-03-18) © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2021 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[ ] Built from source yourself
[x ] Other (Please describe in detail)
</pre>
I built the source with the help from this fork. Not sure if there is another fork with a more stable and/or updated build version.

**Comment by Raymo111** [comment]
Same issue as #159, closing.

**Comment by ribbybbir** [comment]
I think I found the problem. I can't say that the `--redraw-thread`, would work in terms of security perspective, but there's another method that may help otherwise.

sh -c "sudo pm-suspend; i3lock --nofork --beep --no-unlock-indicator --image='/set/user/directory/directory_of_image/' --color=000000FF --centered `--ignore-empty-password` --clock --force-clock --layout-color=FF55FFFF --time-color=FF55FFFF --date-color=FF55FFFF --greeter-color=FF55FFFF --greeter-text='Greeter text line' --no-modkey-text --time-font='Nimbus Mono PS Regular' --date-font='Nimbus Mono PS Regular' --layout-font='Nimbus Mono PS Regular' --greeter-font='Nimbus Mono PS Regular' --date-size=30 --greeter-size=60 --greeter-pos='x--650:y--175' --slideshow-interval=5 --slideshow-random-selection"

Should there be lag for holding down that Enter keyboard button, the `--ignore-empty-password` should suffice for reducing lag for random image change during computer lockscreen.
