### ISSUE TITLE
[Suggestion] Lock/Duration/Unlock Session Log (Option)

### ISSUE THREAD

**Issue by ribbybbir** [Raymo111/i3lock-color#271]
## This issue is a....

<pre>
[ ] Bug
[x ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

I was wondering how to inspect for i3lock-color lock/duration/unlock sessions. I know if somebody would know how to crack the lock, they will attempt to find the logs.

## Expected Behavior

I expect to be able to read the i3lock-color lock/duration/unlock session log(s). If somebody would know how to crack the lock, they will attempt to find the logs. Therefore, an lock/duration/unlock notification alert to an secure email/phone_message protocol would also be desirable.

Oh course, for common intrusions, a security usb key implementation would work (warning, accidental mis-configuration[s] may result in lockout). However, if given enough time and effort, a tampered system can emit its readout with data. Thus, log sessions are still desirable for certain situations.

## Reproduction Instructions

Not applicable at the moment.

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: i3lock: version 2.13.c.4-34-gd846e7c (2022-03-18) © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2021 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[ ] Built from source yourself
[x ] Other (Please describe in detail)
</pre>
I built the source with the help from this fork. Not sure if there is another fork with a more stable and/or updated build version.

**Comment by Raymo111** [comment]
Closing as unclear.
