### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by TheBearodactyl** [Raymo111/i3lock-color#275]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

```
Makefile.am: installing './depcomp'
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
continue configure in default builddir "./x86_64-pc-linux-gnu"
....exec /bin/sh .././configure "--srcdir=.." "--enable-builddir=x86_64-pc-linux-gnu" "linux gnu"
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for gsed... sed
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... configure: error: newly created file is older than distributed files!
Check your system clock 
```
***I've already set my system clock and run*** `sudo hwclock --systohc`, ***so i know that my system clock ain't the problem***
```
==> ERROR: A failure occurred in build().
    Aborting...
```

## Expected Behavior

```
:: Resolving dependencies...
:: There are 2 providers available for i3lock-color:
:: Repository AUR:
    1) i3lock-color  2) i3lock-color-git
Enter a number (default=1): 2

Aur (1) i3lock-color-git-r898.32a1437-1

Total Installed Size:  0.05 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                         [#############################] 100%
(1/1) checking package integrity                       [#############################] 100%
(1/1) loading package files                            [#############################] 100%
(1/1) checking for file conflicts                      [#############################] 100%
(1/1) checking available disk space                    [#############################] 100%
:: Processing package changes...
(1/1) reinstalling i3lock                              [#############################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```

## Reproduction Instructions

paru -S i3lock-color-git

## Environment
Output of `i3lock --version`: N/A
<pre>
i3lock version: N/A
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (git)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
We don't support paru officially. Try clearing your paru cache before reinstalling.

**Comment by TheBearodactyl** [comment]
> We don't support paru officially. Try clearing your paru cache before reinstalling.

sure

**Comment by TheBearodactyl** [comment]
it did the same thing, so i tried building it from the source. same thing happened

**Comment by Raymo111** [comment]
> it did the same thing, so i tried building it from the source. same thing happened
> 

How are you building from source?

**Comment by TheBearodactyl** [comment]
```
git clone https://github.com/Raymo111/i3lock-color
cd i3lock-color
chmod +x install-i3lock-color.sh
./install-i3lock-color.sh
```

**Comment by Raymo111** [comment]
Your system clock is screwed up then. No other explanation.

**Comment by TheBearodactyl** [comment]
found the problem. it was because i had overwritten /bin/ls with the package exa lmao. it was messing with the version check. [Found it here](https://forums.gentoo.org/viewtopic-t-1123106-start-0.html).
the gentoo forums are really useful sometimes
