### ISSUE TITLE
README / manpage / help output

### ISSUE THREAD

**Issue by ghost** [Raymo111/i3lock-color#28]
The last few commits introduced new command line arguments which appear to be (partially?) missing from the docs, such as `--indicator` and `-B blur_strength`.

In general, the documentation appears to be somewhat inconsistent with some arguments only mentioned when executing `i3lock -h` while others can only be found in `README.md`.

The man page appears to be merely a copy from upstream `i3lock` even though it says `i3lock-color` in the title.

This is mildly confusing to new users.

I might be better for everyone – maintainers and users alike – to just scrap the custom man page and help output in favor of just adding an extra line giving the URL of `README.md` on GitHub.

This could reduce maintenance effort and may be better than the current very long and cryptic output produced by `i3lock -h`.

Any opinions on that?

**Comment by PandorasFox** [comment]
I've been meaning to get around to cleaning up the `-h` message and readme - they're actually next on my list, before I move on to the issue(s?) with compositors.

I'd honestly forgotten about the manpage stuff; I haven't ever really tinkered with those before, so help with that would be appreciated :)

**Comment by PandorasFox** [comment]
Alright, I updated all of it in 14af07f5dcbb22533e5bd1898ae04d9ac9d25283. The manpage could probably use a bit of format tweaking (I've never messed with manpages before really, so I have no doubts that I did things incorrectly.)

I'd feel a bit bad having the only docs be in the repo's README, so I went ahead and touched up the manpage some.

**Comment by ghost** [comment]
If every open source developer was that fast at fixing things which are broken, I wouldn't be forced to run an old kernel just to have a working multi-monitor setup.

Thanks.

**Comment by PandorasFox** [comment]
No problem :D

I'm probably not going to be able to work on my projects much this summer, so I'm spending some time to squash long-standing issues.
