### ISSUE TITLE
Feature request: require password to unlock only after certain seconds

### ISSUE THREAD

**Issue by leira** [Raymo111/i3lock-color#288]
## This issue is a....

<pre>
[ ] Bug
[x] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

Currently when i3lock-color locks the screen, it requires password right away. This is annoying when I read a long page or think about some thing on the screen for too long time. I just want to unlock the screen right away. But I'm forced to type the password every time.

## Expected Behavior

Is it possible to implement a feature to require password to unlock only after locked for certain seconds? Thus I will have some time to react and unlock the screen right away. Some thing like kscreenlocker does:
![kscreenlocker](https://camo.githubusercontent.com/12cf81be1b080042253f7bf85ec13bdc18bba47e2ec90174385dd3e140a251e8/68747470733a2f2f692e6962622e636f2f46357977345a772f53637265656e73686f742d32303139303930332d3139323330352e706e67)

## Reproduction Instructions
Start i3lock.

## Environment
Output of `i3lock --version`:
<pre>
i3lock version 2.14.1-non-git © 2010 Michael Stapelberg
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[ ] Built from source yourself
[x] Other (Please describe in detail): NixOS package.
</pre>

**Comment by Raymo111** [comment]
How are you running i3lock-color? You should be running it using something like XSS lock, xautolock, or xidlehook, which have built-in support for timeouts.

**Comment by leira** [comment]
Thanks a lot for the pointers! After some reading, I understand better on how xorg screen lock works.

So i3lock is a just locker app, it locks the screen. It can be launched through shell, or launched by some trigger app. It doesn't handles idle detection or idle timers.

xss-lock is a trigger app. It doesn't lock screen by self, rather it launches a locker app to do it, like i3lock. xss-lock listen[ to the signals from X server and logind service (session management) alike. When a screen saver signal from X server is received, it launches the locker app configured with it.

The X server detects session idle. It sends out screensaver signals when the session is idle for certain time. Such signals are catched by xss-lock if it is running. The timer is configured through `xset s [notify_seconds [cycle_seconds]]` command. E.g. `xset 600 30` configures the X server to send out a screensaver notify signal when idle for 600 seconds, then it will send out a screensaver cycle signal after another 30 seconds.

`xss-lock [-n notify_cmd] [--] locker [arg] ...` can take 2 commands, `notify_cmd` for the notify signal, and `locker` command for the cycle signal. `xss-lock -n dim-screen.sh -- i3lock` with the `xset` setting above will call `dim-screen.sh` after idle for 600 seconds to dim the screen, and then call `i3lock` to lock the screen after another 30 seconds. That is exactly what I want to achieve.

Thanks again! @Raymo111
