### ISSUE TITLE
Font outlines are displayed on the wrong layer with Bahnschrift font

### ISSUE THREAD

**Issue by kStor2poche** [Raymo111/i3lock-color#289]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

Text outlines render on top of the text, as shown in illustration. This is using the `bahnschrift.ttf` font from windows.  

![illustration](https://i.imgur.com/RpjXAqY.png)

## Expected Behavior

Text outlines shouldn't cross the text, even if the text color is tranparent.

## Reproduction Instructions

Execute `i3lock -B 10 -e -k --indicator --radius 140 --pass-{media,power}-keys --no-modkey-text --custom-key-commands --cmd-brightness-up '/home/laio/.config/i3/scripts/light.sh u' --cmd-brightness-down '/home/laio/.config/i3/scripts/light.sh d' --cmd-volume-up '/home/laio/.config/i3/scripts/sound.sh u' --cmd-volume-down '/home/laio/.config/i3/scripts/sound.sh d' --{inside,insidever,insidewrong,line,separator}-color=ffffff00 --ring-color=07080870 --keyhl-color=84ef8970 --bshl-color=fabd2f70 --ringver-color=84b5e070 --ringwrong-color=fb493470 --{time,date,layout,verif,wrong}-font=Bahnschrift --greeter-font='Mononoki Nerd Font Mono' --{time,date,layout,verif,wrong}-size=24 --greeter-size=44 --{time,date,layout,verif,wrong}-color=ffebc670 --{time,date,layout,verif,wrong,greeter}outline-width=1 --{time,date,layout,verif,wrong,greeter}outline-color=07080880 --greeter-color=ffebc670 --date-str='%a %d %b' --greeter-text='ó°¬¾' --verif-text='vÃ©rification' --wrong-text='mauvaise saisie' --noinput-text='vide' --time-pos='ix:iy-22' --date-pos='tx:ty+51' --greeter-pos='ix:h-90' --{verif,wrong}-pos='ix:iy+5'`

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.13.c.5 © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2021 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (which one?)
-> i3lock-color 2.13.c.5-1
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
Does this issue also happen with other fonts?

**Comment by kStor2poche** [comment]
doesn't seem to happen with mononoki nerd font at least,  I'll try to test some other windows fonts for good measure

**Comment by Raymo111** [comment]
That sounds like a font problem then

**Comment by kStor2poche** [comment]
Yeah, other windows font don't behave this way. Bahnshcrift works fine in every other scenario but I'd largely understand that you wouldn't take such a specific issue into account. Thanks for your work and reactivity anyways :)
