### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by Thanatos0173** [Raymo111/i3lock-color#290]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

The command i3lock-color is not found.
## Expected Behavior

The command i3lock-color should be found
## Reproduction Instructions

Using Archcraft.
Installed i3lock-color by cloning the git repo : command not found
Installed i3lock-color using AUR : command not found
Installed i3lock-color usinc pacman : command not found
For other kinds of issues, you can remove this section, or add any aditional info here.
## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 2.13.c.5
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (which one?) (tested with both)
[x] Built from source yourself
[x] Other (Please describe in detail) pacman
</pre>

**Comment by Raymo111** [comment]
The command is `i3lock`.
