### ISSUE TITLE
Modkey stays on screen longer than expected

### ISSUE THREAD

**Issue by ghost** [Raymo111/i3lock-color#291]
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

When you enter an incorrect password, after the "verifying..." message, the "wrong!" error message is shown with the modkeys listed below that. After a certain time the error message disappears, but the modkeys stay on screen.

## Expected Behavior

The modkeys disappear when the error message disappears.

## Reproduction Instructions

1. Enable Capslock or Numlock on your keyboard
2. Run `i3lock`
3. Enter an incorrect password
4. Wait for the error message to display and then disappear

## Environment
Output of `i3lock --version`:
<pre>
i3lock version: 2.13.c.5 (2023-07-28)
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[x] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment]
This is expected behavior. Modkeys are there until you turn it off, 'wrong!' message is there until you start typing again (or for a short while).
