### ISSUE TITLE
No longer being able to unlock the screen

### ISSUE THREAD

**Issue by Samueru-sama** [Raymo111/i3lock-color#296]
## This issue is a....

<pre>
[x ] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior
I updated i3lock-color after having it used for about a year, I keep i3lock-color along with i3 in my '~/.local/bin' dir due to the fact that I run i3 with a patch and not from a official repo so I keep all the i3 stuff there.

To update I simply took the latest binary from release and put it on my `~/.local/bin` dir.

After updating I could not unlock my screen, it constantly said that the password was wrong, I had to log to a different tty and kill i3lock.

Restoring the older binary I had from a backup fixed the issue.

If I take the binary from the release it doesn't work if I put it in either `/usr/bin` or `~/.local/bin`, it locks the screen but fails to unlock when the password is given.

However if I install i3lock from the aur it does work, but moving the binary to `~/.local/bin` makes it fail to unlock the screen again. 

So only my older binary works, the aur package partially works, and the binary from release does not work. 

## Environment
i3lock version: 479ae5e

What's interesting is that the aur package and my older binary are both version 2.13.c.5, however they are not the same, only my older binary works, the binary is 128 KiB while the one from the aur package is 124 KiB.

**Comment by sh1r4s3** [comment]
@Samueru-sama Could you try to copy `pam/i3lock` from the repo to the `/etc/pam.d/` and check whether it will fix the issue.

**Comment by Samueru-sama** [comment]
> @Samueru-sama Could you try to copy `pam/i3lock` from the repo to the `/etc/pam.d/` and check whether it will fix the issue.

Forgot to reply here, the issue no longer happens after I migrated to Artix linux. Both the aur package and the released binary work.

Thanks for the reply though. I'm not sure if the issue was related to the missing pam.d since it only happened with the latest version and also when the binary wasn't in /usr/bin
