### ISSUE TITLE
i3lock: unrecognized option '--insidever-color=#ffffff22'

### ISSUE THREAD

**Issue by xahmad7** [Raymo111/i3lock-color#301]
## This issue is a Problem with i3lock

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Environment
Output of `i3lock --version`:
<pre>
i3lock version:
</pre>

Where'd you get i3lock-color from?

<pre>
[] AUR package (which one?)
[x] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

❯ ./lock-old.sh
i3lock: unrecognized option '--insidever-color=#ffffff22'
i3lock: Syntax: i3lock [-v] [-n] [-b] [-d] [-c color] [-u] [-p win|default] [-i image.png] [-t] [-e] [-I timeout] [-f] [-k]
❯ i3lock --version
i3lock: version 2.15 © 2010 Michael Stapelberg

**Comment by Raymo111** [comment]
You've installed i3lock, not -color.
