### ISSUE TITLE
Bug with date and time color

### ISSUE THREAD

**Issue by cjbassi** [Raymo111/i3lock-color#31]
Currently running the latest version on Arch (did I mention I used Arch) from the AUR package. "--timecolor" sets the color for both the time and date and "--datecolor" doesn't do anything. Really appreciate this fork btw! Just the one issue I've noticed.

**Comment by PandorasFox** [comment]
I'll poke at it this afternoon - I probably messed up a merge commits at some point :v

**Comment by PandorasFox** [comment]
(stuff at my job came up and I've been somewhat very dead - this is on the back burner for now, but I'll look everything over when I can)
