### ISSUE TITLE
datestr doesn't recognize locale

### ISSUE THREAD

**Issue by thurse93** [Raymo111/i3lock-color#35]
Im running the latest version from the AUR (i3lock-color-git r358.206405e-1) with a german locale (LANG=de_DE.UTF-8 set, `locale` gives me the correct output, etc).

`--datestr="%x"` results in "08/02/2017" on the lock screen where it should be "02.08.2017".

**Comment by PandorasFox** [comment]
I'm currently unaware of any localizable variants of `strftime`, but I'll look into this when I can.

**Comment by PandorasFox** [comment]
Hey - the latest commit _should_ fix this - I added `de_DE.UTF-8` to my locale.gen, regenned, and tested with `LANG=de_DE.UTF-8 ./i3lock --datestr="%x" --clock`, and the date separators were periods).

Feel free to double check and verify that.

**Comment by thurse93** [comment]
Jep, it works now! Thank you very much! :)

**Comment by PandorasFox** [comment]
Hey - I did a small tweak to bring locale detection more inline with what i3lock already does. I tested again and it seems to work fine, but can you double check and make sure?

**Comment by thurse93** [comment]
Hi,
I'm on vacation at the moment but I'll check it as soon as is get back.
Regards,

Am 15.08.2017 16:13 schrieb "Chris Guillott" <notifications@github.com>:

Hey - I did a small tweak to bring locale detection more inline with what
i3lock already does. I tested again and it seems to work fine, but can you
double check and make sure?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/chrjguill/i3lock-color/issues/35#issuecomment-322478551>,
or mute the thread

**Comment by thurse93** [comment]
Jep, it still works ;)

**Comment by PandorasFox** [comment]
Awesome, and thanks!
