### ISSUE TITLE
How to launch on Ubuntu

### ISSUE THREAD

**Issue by VanDavv** [Raymo111/i3lock-color#37]
Hi
On the screenshots, this package looks amazing.
I already have `i3lock` working, and I wanted now to use Your extension.
I read documentation, installed required packages, but I don't know what's next. README doesn't cover how to run new, customized lock screen.
Then, I tried to download .git repository and run `lock.sh` script, but i got an error:

> ./lock.sh: 10: ./lock.sh: ./i3lock: not found

If You could help me launching this tool, It would allow someone (maybe even me) to submit PR with updated README

**Comment by PandorasFox** [comment]
As for the last note - see #36, this isn't going to be covered/put in the readme. You should be using a package and not installing from source if you don't know what you're doing.

As for the reason `./i3lock` isn't found - it's trying to run the version from the local directory, i.e. the version that is generated after your run `make` in the cloned directory.

**Comment by chrjguill** [comment]
As for the last note - see #36, this isn't going to be covered/put in the readme. You should be using a package and not installing from source if you don't know what you're doing.

As for the reason `./i3lock` isn't found - it's trying to run the version from the local directory, i.e. the version that is generated after your run `make` in the cloned directory.

**Comment by PandorasFox** [comment]
On that note - if you don't know what `make` is, you shouldn't be using a fork of a screen locker. Do some reading [this](http://www.tldp.org/HOWTO/Software-Building-HOWTO-3.html) and doing deep reading (i.e. googling everything you come across that you don't understand, and keep reading until you feel you understand the background enough)

**Comment by VanDavv** [comment]
I know what Makefile is, just didn't saw it. However, readme also didn't mention about it. 
I'm using ubuntu system, and readme specifies only arch package
