### ISSUE TITLE
Unable to get i3lock-color up and running with i3lock-fancy-dual

### ISSUE THREAD

**Issue by cjmick** [Raymo111/i3lock-color#43]
Ok, I have i3lock-color installed along with i3lock-fancy-dual monitors. created a lock.sh file with the example script hit my short cut invoking i3lock like it says. I get the regular i3lock, not the colored one. I have the script, tried putting it to a shortcut and all I got were config errors. My i3lock config is bindsym $mod+shift+x exec i3lock. When I run the lock script by itself I get an error saying ./i3lock: no such file or directory. I am runing Arch linux. I put the lock script in my ~/.config/i3 folder.

**Comment by PandorasFox** [comment]
> When I run the lock script by itself I get an error saying ./i3lock: no such file or directory.

If you're using the [aur package ](https://aur.archlinux.org/packages/i3lock-color-git) then i3lock will just be in your $PATH, in /usr/bin. Remove the leading `./` and you'll be good to go.

Closing anyways since it's not really an issue with i3lock.

**Comment by cjmick** [comment]
Yes, thats what I have for my keybind, but it still isn't working

**Comment by cjmick** [comment]
It just brings up the old i3lock not the config for color and its not blurred

**Comment by PandorasFox** [comment]
I can't really help you much, since this kinda requires you to understand how $PATH works, and how to properly call the right binary. If you've install the package I linked, then you should simply have to do `i3lock` and it'll invoke the `i3lock` binary that this package provides - you should not be able to have both the old version and my fork installed at the same time through the AUR since they provide the same package (`i3lock`).

**Comment by cjmick** [comment]
Yes, sorry to bug you. I figured it out. I didn't include the path to the executable script. All is working now. Appreciate the effort

**Comment by hk3wxy** [comment]
> > When I run the lock script by itself I get an error saying ./i3lock: no such file or directory.
> 
> If you're using the [aur package ](https://aur.archlinux.org/packages/i3lock-color-git) then i3lock will just be in your $PATH, in /usr/bin. Remove the leading `./` and you'll be good to go.
> 
> Closing anyways since it's not really an issue with i3lock.

You actually solve my issue!
Thank you!
