### ISSUE TITLE
Compiling on ARM doesn't work

### ISSUE THREAD

**Issue by PandorasFox** [Raymo111/i3lock-color#44]
Probably due to SSE stuff. I should get the makefile or something to work around that, or provide a makefile recipe that works fine for ARM.

**Comment by PandorasFox** [comment]
Potentially fixed in https://github.com/PandorasFox/i3lock-color/commit/4318dbe05142dd7229d4b44565b482ed50a7c381

I need to actually check that

**Comment by toshipiazza** [comment]
Just need to ifdef out the `#include <xmmintrin>` in `blur_simd.h` and it compiles/runs for me on ARM

**Comment by PandorasFox** [comment]
Oooh, thanks. I should've thought of that earlier.

**Comment by PandorasFox** [comment]
Fixed in 599158e2eed46bbab4f782fa7c39ce5d44c13cff

Thanks!
