### ISSUE TITLE
Input lag when using a background picture and blur at the same time

### ISSUE THREAD

**Issue by Nutcake** [Raymo111/i3lock-color#45]
These are my current commandline arguments:
`i3lock -k -S 0 --ringcolor=212121aa --timesize=90 --timefont="Google Sans Regular" --datefont="Google Sans Regular" --datesize=20 --timecolor=ffffffaa --datecolor=ffffffaa --linecolor=212121aa --insidecolor=212121aa -i ribbon.png --timepos="2037:115"`

Ribbon.png is a black transparent ribbon across my monitors to add a darker background to the clock. This looks like [this](https://a.pomfe.co/fbyved.jpg) for reference. Issue is, when entering my password, some keystrokes are delayed by up to half a second, depending on how fast I type. When I type slowly there is no or minimal delay. This also stops happening when I either disable blur or remove the background image, but I would like to keep my setup as is.

**Comment by PandorasFox** [comment]
Hm, I can think of a couple reasons why. I may have to rewrite the redraw stuff to only redraw the part of the screen with the indicator.

Can you upload the ribbon.png as well? I'll poke around with it some and see if I can reproduce. My setup has a 2560\*1440 + 1920\*1080 display, so if it's related to raw resolution I should be able to repro it.

What CPU do you have, as well?

**Comment by Nutcake** [comment]
[Here](https://a.pomfe.co/kvldyg.png) is the ribbon.png, and my CPU is a Ryzen R5 1600

**Comment by PandorasFox** [comment]
Hm, weird. I have a Ryzen 1700 now and haven't noticed any problems, so I'll definitely try and figure out what's up.

Here's what I'm running to test it:

`./i3lock -k -S 0 --ringcolor=212121aa --timesize=90 --timefont="Google Sans Regular" --datefont="Google Sans Regular" --datesize=20 --timecolor=ffffffaa --datecolor=ffffffaa --linecolor=212121aa --insidecolor=212121aa -i ~/black\ banner.png --timepos="1100:1200" -B 10`

which looks like:

![2017-11-19_11 22 37-abeb88](https://user-images.githubusercontent.com/3235827/32992717-fbdd16ac-cd1b-11e7-841e-428c605723bb.png)

I haven't noticed any input lag just by default. However, there's a decent amount of lag between a failed input and it showing the next keystrokes.

I'll see if I can reproduce this by like, spinning up a few VMs and eating up more of my resources.

**Comment by Nutcake** [comment]
Using your command, I also get input lag.

I've noticed that it doesn't happen every time and usually is worst on the last few characters of the password. I've recorded a video of this issue, typing as fast as possible to help demonstrate the problem. It works fine the first time, but you should be able to hear on the second try, the last two characters are delayed by around half a second after I've already hit enter ([Video link](https://my.mixtape.moe/pzxhgt.m4v)). It happens regardless of CPU and RAM usage.

**Comment by PandorasFox** [comment]
Hm, I'll try to see what I can do to reproduce this, then. I don't think I've ever had that happen to me, so once I can repro this I should be able to get it fixed.

I have a few hunches, but that's really weird.

**Comment by PandorasFox** [comment]
Yeah, I like, can't reproduce this on my system. I can occasionally get it to lag a bit after a failed authentication (although, I'm pretty sure that's a separate issue).

Can you grab the [keylayout branch](https://github.com/chrjguill/i3lock-color/tree/keylayout) and build from there, then re-run with `--debug`, and attach the output from that?

You'll probably want to scrub the "current password=" lines from the output, or change your password beforehand to something like, well, "password". If you can attach one debug output from a usual case, and one from when it does the input lag, that should help a decent amount.

The redraw stuff _should_ be getting called each time there's an input, so either there's some weird input lag at your system level that keeps i3lock from getting it on time, or there's some bug where it calls the redraw() stuff consistently but nothing happens.

I've noticed some occasional weird input lag on linux since switching to Ryzen (i.e. typing in Vim will occasionally lag behind for a couple seconds), but it's fairly infrequent and hasn't happened to me in i3lock, so I dunno. This is weird.

**Comment by Nutcake** [comment]
Here's the log for when the issue happens:

```[i3lock-debug] device = 3
[i3lock-debug] Querying monitors using RandR 1.5
[i3lock-debug] 3 RandR monitors found (timestamp 41983)
[i3lock-debug] found RandR monitor: 1920 x 1080 at 1280 x 0
[i3lock-debug] found RandR monitor: 1280 x 1024 at 0 x 0
[i3lock-debug] found RandR monitor: 1280 x 1024 at 3200 x 0
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] device = 3
[i3lock-debug] redraw_screen(unlock_state = 0, auth_state = 0) @ [1511132924]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] device = 3
[i3lock-debug] Querying monitors using RandR 1.5
[i3lock-debug] 3 RandR monitors found (timestamp 41983)
[i3lock-debug] found RandR monitor: 1920 x 1080 at 1280 x 0
[i3lock-debug] found RandR monitor: 1280 x 1024 at 0 x 0
[i3lock-debug] found RandR monitor: 1280 x 1024 at 3200 x 0
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] Watching window 0x06c00008
[i3lock-debug] Read event of type 18
[i3lock-debug] UnmapNotify for 0x06c00008
[i3lock-debug] device = 3
[i3lock-debug] Querying monitors using RandR 1.5
[i3lock-debug] 3 RandR monitors found (timestamp 41983)
[i3lock-debug] found RandR monitor: 1920 x 1080 at 1280 x 0
[i3lock-debug] found RandR monitor: 1280 x 1024 at 0 x 0
[i3lock-debug] found RandR monitor: 1280 x 1024 at 3200 x 0
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] device = 3
[i3lock-debug] redraw_screen(unlock_state = 0, auth_state = 0) @ [1511132924]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] redraw_screen(unlock_state = 0, auth_state = 0) @ [1511132924]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] redraw_screen(unlock_state = 0, auth_state = 0) @ [1511132925]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] redraw_screen(unlock_state = 0, auth_state = 0) @ [1511132926]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] current password = w
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0) @ [1511132927]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] current password = we
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0) @ [1511132927]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] current password = web
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0) @ [1511132927]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] current password = webs
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0) @ [1511132927]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] redraw_screen(unlock_state = 1, auth_state = 0) @ [1511132927]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] redraw_screen(unlock_state = 1, auth_state = 0) @ [1511132927]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] redraw_screen(unlock_state = 1, auth_state = 0) @ [1511132927]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] redraw_screen(unlock_state = 1, auth_state = 0) @ [1511132927]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] current password = websi
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0) @ [1511132927]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] current password = websit
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0) @ [1511132927]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] current password = website
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0) @ [1511132927]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] current password = websites
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0) @ [1511132928]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] redraw_screen(unlock_state = 1, auth_state = 0) @ [1511132928]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] redraw_screen(unlock_state = 0, auth_state = 1) @ [1511132928]  
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px  
[i3lock-debug] successfully authenticated  
[i3lock-debug] restoring focus to X11 window 0x06a00003  
```



And here without (me noticing) any lag:

```[i3lock-debug] device = 3
[i3lock-debug] Querying monitors using RandR 1.5
[i3lock-debug] 3 RandR monitors found (timestamp 131265423)
[i3lock-debug] found RandR monitor: 1920 x 1080 at 1280 x 0
[i3lock-debug] found RandR monitor: 1280 x 1024 at 0 x 0
[i3lock-debug] found RandR monitor: 1280 x 1024 at 3200 x 0
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] device = 3
[i3lock-debug] redraw_screen(unlock_state = 0, auth_state = 0) @ [1511133697]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] device = 3
[i3lock-debug] Querying monitors using RandR 1.5
[i3lock-debug] 3 RandR monitors found (timestamp 131265423)
[i3lock-debug] found RandR monitor: 1920 x 1080 at 1280 x 0
[i3lock-debug] found RandR monitor: 1280 x 1024 at 0 x 0
[i3lock-debug] found RandR monitor: 1280 x 1024 at 3200 x 0
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] Watching window 0x05200008
[i3lock-debug] Read event of type 18
[i3lock-debug] UnmapNotify for 0x05200008
[i3lock-debug] device = 3
[i3lock-debug] Querying monitors using RandR 1.5
[i3lock-debug] 3 RandR monitors found (timestamp 131265423)
[i3lock-debug] found RandR monitor: 1920 x 1080 at 1280 x 0
[i3lock-debug] found RandR monitor: 1280 x 1024 at 0 x 0
[i3lock-debug] found RandR monitor: 1280 x 1024 at 3200 x 0
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] device = 3
[i3lock-debug] redraw_screen(unlock_state = 0, auth_state = 0) @ [1511133697]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] redraw_screen(unlock_state = 0, auth_state = 0) @ [1511133697]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] redraw_screen(unlock_state = 0, auth_state = 0) @ [1511133698]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] current password = w
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0) @ [1511133699]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] current password = we
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0) @ [1511133699]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] current password = web
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0) @ [1511133699]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] current password = webs
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0) @ [1511133699]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] redraw_screen(unlock_state = 1, auth_state = 0) @ [1511133699]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] redraw_screen(unlock_state = 1, auth_state = 0) @ [1511133699]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] redraw_screen(unlock_state = 1, auth_state = 0) @ [1511133699]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] current password = websi
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0) @ [1511133699]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] current password = websit
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0) @ [1511133699]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] current password = website
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0) @ [1511133699]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] current password = websites
[i3lock-debug] redraw_screen(unlock_state = 2, auth_state = 0) @ [1511133699]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] redraw_screen(unlock_state = 1, auth_state = 0) @ [1511133699]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] redraw_screen(unlock_state = 0, auth_state = 1) @ [1511133699]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] successfully authenticated
[i3lock-debug] redraw_screen(unlock_state = 0, auth_state = 1) @ [1511133700]
[i3lock-debug] scaling_factor is 1, physical diameter is 187 px
[i3lock-debug] restoring focus to X11 window 0x05000003
```

Don't worry, "websites" is not my password, just needed to find a word that I could type fast enough to encounter the issue.
Also, I don't think this is something that goes on and off, but feels more like the effect is sometimes worse and sometimes better to the point of not being able to notice.

**Comment by PandorasFox** [comment]
Hm, just judging by the timestamps, it doesn't _seem_ like anything should be happening.

I'll keep trying to see if I can reproduce this on one of my other machines. I tried for a good 30 minutes yesterday to get it to occur, but I just can't get it to happen for me.

**Comment by PandorasFox** [comment]
So, I know _what's_ happening, but I don't really know _why_ still. I have some hunches (low RAM perhaps), but no idea why really.

Basically, `handle_key_press` will invoke `redraw_screen`, which is blocking. So if you press keys while it's redrawing, it'll lag behind and then parse multiple keystrokes, then redraw again rapidly.

I usually see this when PAM is authenticating (and blocking). I'm working at splitting off perioidic redraws into their own pthread, but that won't fix this specific issue (probably).

My best guess is that you're running low on RAM (and then allocating the canvasses and stuff takes a split second), or something is preempting i3lock for a second (which shouldn't happen really).

**Comment by Nutcake** [comment]
I don't think low RAM is the issue, this system has 16GB of DDR4 and the issue also happens on fresh boot. This also doesn't happen on my laptop with 6GB of DDR3.

**Comment by PandorasFox** [comment]
Weird. Can I get your full system specs?

I get nothing with:
* Ryzen 7 1700
* 16 GB DDR4
* 2560\*1440 monitor + 1920\*1080 monitor
* 120GB SSD for `/` and `/home/`

I imagine that our systems aren't terribly different, aside from CPU and perhaps the specifics of the resolutions.

**Comment by Nutcake** [comment]
Here's my main system with the issue:

- Ryzen 5 1600
- 16GB DDR4 @ 2666Mhz
- 1280x1024:60 + 1920x1080:60 + 1280x1024:60
- 120GB SSD for `/` and `/home` as separate partitions; 3TB HDD for media and my `~/.local` and `~/.cache` folders are symlinked to there because of size constraints on the SSD.
- Nvidia GTX 1070 8G that gets isolated at early boot for use in a KVM VFIO setup (I start the VM only when I need it and all testing has been done with it not running).
- Nvidia GTX 770 2G as the main GPU the X server uses

Any my laptop that doesn't have the issue is a Thinkpad T430 with an i3-3320M, 6GB of DDR3, a 120GB SSD, and is using the integrated HD4000 GPU.

**Comment by PandorasFox** [comment]
Yeah, that's mostly similar to what I have. Although - I have an r9 290. It might be the case that it's an issue with nvidia X11 drivers, maybe? 

My laptop has an i7-3632QM, 8GBDDR3, and a 120GB SSD and is using integrated as well (and also doesn't have a problem), so that's expected, at least.

I seem to recall someone having a problem with i3lock-color and nvidia before, but I don't see anything in any of the other issues, oddly enough. Sadly, I can't really test that currently.

(Also, I still need to get another cheap GPU so I can set up KVM again. I might grab like, a 750 TI or something so that I can also test nvidea drivers or something, at some point)

**Comment by Nutcake** [comment]
Hmm, I don't have another System with an Nvidia card to test this on and installing nouveau drivers on my main rig would be a pretty massive hassle because of the way my KVM passthrough is set up (and last time I tried nouveau it didn't work at all), so I'm afraid I don't know how I could further pinpoint this issue...

**Comment by PandorasFox** [comment]
Given that no one else apparently has this issue, it may be something else entirely - that's just the only thing I can think of currently. I'll try to see if I can borrow a friend's machine with an nvidia gpu to replicate.

**Comment by keeakita** [comment]
I was able to observe a bit of input lag on my machine at a higher resolution, same as OP described. But at lower resolutions it's fine.

- AMD 8350 FX
- Nvidia 750Ti
- 16GB DDR3
- Lagging: 2520x1575:60 + 1350x2160:60 + 3840x2160:60 (one 4k, two virtually scaled)
- No lag: 1920x1080:60 + 1680x1050:60 + 1440x900:60

**Comment by Nutcake** [comment]
I tried disabling two of my three monitors, so using a single 1920x1080 monitor, and it definitely reduced the input lag to the point where it's unnoticeable.

**Comment by PandorasFox** [comment]
I'm assuming it's something between Cairo, Nvidia, and multiple monitors. @oslerw and I tried some profiling stuff last night but couldn't really come up with anything.

I'm going to be trying something else today - I'm going to look at reducing the number of allocs/frees at each resraw tick by caching the Cairo canvasses. I'll see how that goes.

**Comment by Nutcake** [comment]
commit 046784b4c40cf21228f7dd6bcad202aea3c75633 seems to fix this issue, however startup time is much worse than current stable with blur enabled.

**Comment by PandorasFox** [comment]
Huh, interesting.

About how much worse would you say it is?

**Comment by Nutcake** [comment]
Using the same blur level `--blur=7` for both, stable takes ~1.5s while the current master takes ~8s.
Edit: Never mind I forgot to disable debug flags before compiling, whoops!
Though another thing I noticed is that my ribbon looks a whole lot darker than before, almost as if it's being rendered twice and overlapping. But that's not much of an issue for me, so I think this can be closed here.

**Comment by PandorasFox** [comment]
The ribbon change might've been another bugfix that was rolled into it - I was doing some stuff incorrectly before with it that lead to some incorrect alpha levels, so it's probably just that you're seeing the "right" values now.

And awesome, glad that that seems to have fixed it!
