### ISSUE TITLE
Left aligned text (time/date)

### ISSUE THREAD

**Issue by tadly** [Raymo111/i3lock-color#47]
Without having read any of the source, it seems as the text position (for both time and date) are calculated from a center point?
When manually left-aligning the time and date, this will ultimately cause the alignment to break as soon as the total length (in pixel) of either of them changes (new day, new month etc.)

## (Somewhat) properly aligned
![aligned](https://user-images.githubusercontent.com/503647/33063801-d77cd840-cea3-11e7-9e9a-9b54e7beee76.jpg)

## Alignment broken
![unaligned](https://user-images.githubusercontent.com/503647/33063802-d7970490-cea3-11e7-8c08-ee49bf4087cd.jpg)

## Command (stripped to the relevant stuff)
```sh
i3lock -n \
    --indicator \
    --clock \
    --indpos="60:1020" \
    --timepos="ix-130:iy-105" \
    --datepos="tx+82:ty+25" \
    --timestr="%H:%M" \
    --datestr="%A, %m %b %Y" \
    --timesize=20 \
    --datesize=20 \
    --radius=20 \
    --veriftext="" \
    --wrongtext=""```

**Comment by PandorasFox** [comment]
Hm, it might be pretty easy to do this. I might give it a shot today.

Otherwise I'll have to shelve this until after my term projects.

**Comment by PandorasFox** [comment]
Yeah, the stuff responsible is here: https://github.com/chrjguill/i3lock-color/blob/master/unlock_indicator.c#L523

I'll change it so that with text centering disabled, it'll no longer take into account the width/2 or whatever.

I'll also probably add a right-align option so that if you want to do that, it should work just as well.

**Comment by PandorasFox** [comment]
done with 2afbb6884901a7a9a22c9cb0ca8769aa6271a471

You'll need to hop onto the keylayout branch to use it now; I'm still waiting to hear on #39 before I merge it back to master.

**Comment by tadly** [comment]
tested and working :)
Thanks a bunch!

**Comment by PandorasFox** [comment]
No problem! It never occured to me that that might be needed, but it seems pretty obvious in retrospect. Thanks for letting me know!
