### ISSUE TITLE
Command line options not recognized in 2.10

### ISSUE THREAD

**Issue by seongminp** [Raymo111/i3lock-color#51]
Forgive me if this is my mistake. I have compiled version `2.10-non-git`. The binary does not seem to recognize options that diverge from the original i3lock. My launch command is:

`i3lock -n -i $HOME/wallpaper.png \
    --insidecolor=373445ff --ringcolor=ffffffff --line-uses-inside \
    --keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000 \
    --insidevercolor=fecf4dff --insidewrongcolor=d23c3dff \
    --ringvercolor=ffffffff --ringwrongcolor=ffffffff --indpos="x+86:y+1003" \
    --radius=15 --veriftext="" --wrongtext=""`

The error message I get is:
`i3lock: unrecognized option '--insidecolor=373445ff'`. This goes on for all the other options if I delete the problematic one.

I thought maybe I was using the wrong, unforked binary. So I tried the same command(without the new `--indpos` option) with release `2.9.1-c`(which says it is version `2.8-non-git` when I ask `i3lock -v`), and that version worked. Therefore I had to conclude either I was missing a newly introduced launch procedure or there was a bug with the new release. 

Would you be able to shed some light on this? Thank you so much for maintaining this repository!

**Comment by PandorasFox** [comment]
I'll look into this now. I've been forgetting to tweak the VERSION_NUMBER file with releases; that's my bad.

**Comment by PandorasFox** [comment]
Actually - 

Can you try running it all on one line? The `\` is supposed to just be there to break lines for the included `lock.sh` to be more readable (it escapes the newline so that it'll work when split onto multiple lines, but if you're condensing it down to one line, you'll want to remove those.

I know that I tested the `lock.sh` (and a few of my other lock scripts) and they all looked the same, which is what I go for. All the options _should_ still work.

**Comment by seongminp** [comment]
I found the problem. I was using the 2.10 tar.gz file in https://github.com/chrjguill/i3lock-color/releases, but when I clone the repo directly and build i3lock-colors it all works nicely. Don't know why it didn't occur to me to directly clone the repo..

**Comment by PandorasFox** [comment]
Oh, jeez. GitHub broke the release and used the tag from upstream i3lock's master branch for the build. 

I'll try to get that tarball fixed.

**Comment by PandorasFox** [comment]
Sorry about that. Should be fixed with 2.10.1-c
