### ISSUE TITLE
clock disappears for a short time on wrong password

### ISSUE THREAD

**Issue by AUTplayed** [Raymo111/i3lock-color#58]
If you start i3lock with the following arguments:

`i3lock --clock --timepos="x-90:h-ch+30"`

so that the time is outside the circle and enter a wrong password, the time disappears as the circle outputs "wrong!" and reappears after the "wrong!" disappears again.

I hope that makes sense...

**Comment by PandorasFox** [comment]
Please read [the manpage](https://github.com/PandorasFox/i3lock-color/blob/master/i3lock.1) (`man ./i3lock.1`, or just `man i3lock` if you've done a `sudo make install`).

`--force-clock` exists.

**Comment by AUTplayed** [comment]
Sorry! Also thanks a lot.
