### ISSUE TITLE
Can't unlock on Gentoo

### ISSUE THREAD

**Issue by kenogo** [Raymo111/i3lock-color#61]
I've tried to install this by cloning the master branch AND by downloading the latest release zip. Build and installation don't give me any errors in either case. But when i start i3lock and enter my password, it tells me that it's wrong (I made very sure that it's not wrong 😉). I then have to kill it from a TTY session in order to access my desktop again.

I've uninstalled it and installed the official i3lock (v2.8) from the Gentoo repositories and the latest release (v2.10 downloaded as a tar.bz2 archive). Both work without issues, so there's gotta be a problem with your fork.

By the way, I'm using a German keyboard layout. However, I've already tried changing my password to something where the keyboard layout doesn't matter (pure number combination), without success.

**Comment by kenogo** [comment]
Okay, so it seems that installing the official i3lock, then installing your fork, and finally uninstalling the official one made it work. Your fork now gives me a memory leak, though, will open a new issue for that.

Edit: Just saw there's already an issue for that and it's fixed in the dev branch. So I won't open a new issue.

**Comment by PandorasFox** [comment]
>  it's fixed in the dev branch. 

all the commits from `dev` are in `master` right now, but if it's the one related to cairo font stuff, then yeah, that one's more of an upstream issue right now.

Also, it sounds like the issues with it installing on gentoo may have been that my fork isn't installing the PAM file correctly on Gentoo. I'm away from my rig with a gentoo vm for the holidays, so I can't really test that, but that's what my hunch is.

**Comment by owenthewizard** [comment]
Put this in `/etc/pam.d/i3lock` to fix not being able to unlock on Gentoo:

    auth include system-auth

**Comment by PandorasFox** [comment]
ah, yeah, that'll be it.

I know that on arch, they had to modify the install files a bit to make the pam files install to the right place.

There's a way to specify where to install it to with gnu autotools, but I forget how to do that off the top of my head.

**Comment by kenogo** [comment]
`auth include login` also seems to work. So having either of the two in there makes it possible to login, otherwise you can't.
