### ISSUE TITLE
Control the thickness of the ring

### ISSUE THREAD

**Issue by zhou13** [Raymo111/i3lock-color#67]
It seems there is no way to control the thickness of the unlock ring.  I can control it radius by using `--radius` but not its thickness.  I tried `--bar-width` and `--bar-base-width` but it seems that they are not relevant.

**Comment by PandorasFox** [comment]
Please check the manpage - `--ring-width` is a valid option.

**Comment by zhou13** [comment]
It works but I cannot find `--ring-width` in https://github.com/PandorasFox/i3lock-color/blob/master/i3lock.1.

**Comment by PandorasFox** [comment]
Weird, I know it was in there at some point. Guess I lost it when I rearranged the manpage
