### ISSUE TITLE
How to specify custom font?

### ISSUE THREAD

**Issue by mateuszlewko** [Raymo111/i3lock-color#68]
How do I specify custom font used for clock or date?
I see there is an option `--timefont`, but I don't know what should I specify.
Let's say I have a font called `DejaVu Sans`. Specifying this name doesn't change anything. I've also tried `DejaVu-Sans`.
What am I doing wrong?

**Comment by PandorasFox** [comment]
How exactly are you running i3lock?

i.e. here's (sorta) what my lock script looks like:

```
i3lock --timefont "monofur" --datefont "monofur" --clock [...]
```

If you check out the dev branch (fdd03ea1e39c953167a0b99c520c2c7c9ab9ee58 is the latest commit), it might work a bit better. I stopped using fontconfig's font lookups and i3 handles fontconfig interfacing, so you may want to try poking at your fontconfig. (I'd say maybe just try some basic ones like `monospace`, `serif`, and maybe `Arial` or something at first just to see if it works at all)

**Comment by PandorasFox** [comment]
This is in master now with the new release, so please give it a try when you can.

**Comment by mateuszlewko** [comment]
Okay, I'll check it out and let you know soon.

**Comment by clayrisser** [comment]
I get the following error. I'm directly running the built binary.

```
unrecognized option '--timefont'
```

**Comment by clayrisser** [comment]
Super weird, but I got it to work with the following release.

https://github.com/PandorasFox/i3lock-color/releases/tag/2.10.1c

Looks like the refactor broke some things.

**Comment by PandorasFox** [comment]
It's `--time-font` now, since half the fonts had the extra hyphen and half didn't, so I made it more consistent.

**Comment by mateuszlewko** [comment]
So changing font now works (as long as its name is < 31 characters long). Also bug with text being cut is fixed. Thanks for that!

**Comment by PandorasFox** [comment]
If the issue with font name length is an issue, let me know and I'll bump it to 64 or something. I couldn't find any common fonts that long so hopefully it's not a problem ever

**Comment by clayrisser** [comment]
Please don't close this issue until it is documented. There are many other properties that don't seem to work either. How am I supposed to just know what they were changed to?

**Comment by mateuszlewko** [comment]
@jamrizzi  Feel free to open this issue if you want. Man pages have been updated so check out `man i3lock` for description of parameters.

**Comment by PandorasFox** [comment]
> Please don't close this issue until it is documented. There are many other properties that don't seem to work either. How am I supposed to just know what they were changed to?

https://github.com/PandorasFox/i3lock-color/blob/master/i3lock.1#L279

The manpages _have_ been updated - I did make sure that every option listed. There's a [decent number here](https://github.com/PandorasFox/i3lock-color/blob/master/i3lock.c#L1030) and it's possible that I missed one or two.

This is actually why I'm in the middle of working on making a wiki instead of a manpage. Yeah, a manpage works offline, but a github wiki page is.... loads easier to deal with than manpage formatting.

If you want to give some _useful_ feedback, listing some arguments that "don't seem to work" would be more useful than just _saying_ there's some that don't work. I do this in my spare time as a full-time student, so updating the docs is pretty low on my list of priorities - but it _has_ been done.

**Comment by clayrisser** [comment]
Yeah, I totally understand. Sorry for the vague comment. Great work!

**Comment by teamdandelion** [comment]
+1 for switching to a wiki instead of a man page - as a user, I would have preferred that (and it's easier to keep up-to-date).

The man page can just link to the wiki, I think it's pretty reasonable to assume that users of this software have a web browser ;)

**Comment by PandorasFox** [comment]
Yeah, I'll definitely be working on that pretty soon, although it might get pushed back to the end of the semester depending on how busy my static analysis class gets.
