### ISSUE TITLE
Unrecognized option --textcolor

### ISSUE THREAD

**Issue by bpingris** [Raymo111/i3lock-color#73]
The script doesn't recognize the option --textcolor
here's the output when I use this option

```
i3lock-color: unrecognized option '--textcolor=ffffffff'
i3lock-color: Syntax: i3lock [-v] [-n] [-b] [-d] [-c color] [-u] [-p win|default] [-i image.png] [-t] [-e] [-f]
Please see the manpage for a full list of arguments.

```
to install it I simply cloned the repo and did : 
`autoreconf -i && ./configure && make`

no errors occured and the examples scripts work well

**Comment by PandorasFox** [comment]
https://github.com/PandorasFox/i3lock-color/commit/8bf03bab9da8905b84034b40e24feaa0f337c994

That arg got deprecated in favor of a handful of other args (verifcolor, wrongcolor, layoutcolor) to make things a bit more granular.
