### ISSUE TITLE
Feature request: Add shadow around the text for readability

### ISSUE THREAD

**Issue by bew** [Raymo111/i3lock-color#77]
Hello,

I use the `--blur` option to screenshot & blur the screen, and I'm having a hard (impossible?) time to choose the color of the text (clock & date), because the blurry background can sometime be of the same or close to the color of the text, making the text unreadable.

Adding a light shadow under/around the text would fix this issue, by making the text kind-of above the background.

Another way (simpler to implement I think) would be to allow to tint the whole generated background with a color. For example `00000033` for this color would make the whole background a little bit darker, so the text (assuming it's white) is properly readable.

What do you think?

**Comment by PandorasFox** [comment]
Text shadowing in cairo would be a bit tricky. I can think of a few ways to do it (every time [draw_text](https://github.com/PandorasFox/i3lock-color/blob/master/unlock_indicator.c#L273) gets invoked, there can be a check for a text.shadow option, then we can redraw the same text, shifted a bit, and all black or something), but none off the top of my head that I really like.

As for the latter, you can actually already do that - --blur and --image aren't mutually exclusive. Any image you specify will get layered over the blurred background, and you should be able to tile images with an alpha channel too. You could either just pre-gen an image that's the same dimensions as your screen geometry and is `#00000033`, or you could probably just do that, but 1x1 and then tell i3lock to tile it.

**Comment by bew** [comment]
About 1. I see your point, maybe a text outline would be enough? (something like [this](https://stackoverflow.com/questions/8049764/how-can-i-draw-text-with-different-stroke-and-fill-colors-on-images-with-python)).

Edit: at first I was thinking about:
![screenshot_20180228-010043](https://user-images.githubusercontent.com/9730330/36778956-2a3d6492-1c23-11e8-848f-05f965f8e794.jpg)
But if I understand correctly, this is not directly available with cairo.

About 2. Thanks for the trick! I'll try that for now.

Now I wonder if it'll be possible one day to specify N colored rectangle(s), to do this effect on some parts of the screen (e.g: where our clock is, or the bottom of the screen, ...). Should I open a new issue for this/discuss this?

**Comment by PandorasFox** [comment]
A text outline might sorta work, but doesn't look the best, in my opinion. If I do text shadowing, I'll want to do it the "right" way (with some blurring to smooth it out).

The rectangles would sorta possible, but again, you can pretty much preprocess it and pass it in.

If I end up doing a big rewrite to handle config files to allow for different configs for multiple screens, it'd become pretty trivial to just allow arbitrary rectangles of different color. But until then, setting it up on the CLI would be a gigantic pain, so it wouldn't be done until then.

**Comment by bew** [comment]
> The rectangles would sorta possible, but again, you can pretty much preprocess it and pass it in.

Not so easy to preprocess I think, as you loose the variables for the placement (relative to text/indic or to the screen).

> If I end up doing a big rewrite to handle config files to allow for different configs for multiple screens, it'd become pretty trivial to just allow arbitrary rectangles of different color.

Sounds good, if you need help I might be interested and give it a try :smiley: 

> But until then, setting it up on the CLI would be a gigantic pain.

With the current CLI config, I agree. I've been thinking about another way to organize the CLI args, that would allow more advanced graphic stuff (like custom text widget or rectangles) later, I'll probably open another issue about that.

**Comment by PandorasFox** [comment]
Anything that'd require reworking the CLI stuff will probably be dropped/ignored, since I think the better solution is to support config files. That's just inherently more flexible.

(As in, purely extending the CLI parsing isn't really what I want to do/it'll probably limit config stuff going forwards. I don't want to break compatibility multiple times, so the next break I do will be pretty big)

**Comment by PandorasFox** [comment]
Been playing around with this some. I dunno if there's any easy way to implement this with Cairo in a way that doesn't suck, frankly.

**Comment by PandorasFox** [comment]
Yeah, I'm going to close this for now since I don't think it'll really be viable with how i3lock-color works right now.
