### ISSUE TITLE
veriftext centering

### ISSUE THREAD

**Issue by gpakosz** [Raymo111/i3lock-color#81]
Hello, I tried using the following configuration:
```
--verif-font="FontAwesome"
--veriftext=""
--verif-size="100"
```

The `` character is [an unlocked lock icon (`U+F13E`) from Font Awesome 4](https://fontawesome.com/v4.7.0/icon/unlock-alt/). While it's displayed properly, in the sense that it's using the proper font, the glyph is not centered in the middle of the ring.

Is this a vertical alignment bug? If not, is there a way to offset the verif text vertically please?
![image](https://user-images.githubusercontent.com/553208/37220143-f525acf6-23c5-11e8-8949-2524cecf4f06.png)

**Comment by PandorasFox** [comment]
Oof, I hadn't tested glyphs like that. I have some hunches as to why, but text isn't vertically centered right now (I think mostly because of the assumption that different text objects would be consistent heights and thus normalized, but that's not the case with fontawesome glyphs)

I can probably poke at using the text extents height and then center stuff. Hopefully it doesn't break existing formatting too much

**Comment by gpakosz** [comment]
I realize what I'm trying to achieve somewhat also calls for having a way to specify a different font than `wrongfont` for modif. Is it possible to have `--modif-font` and `--modifsize`?

**Comment by PandorasFox** [comment]
Currently, no, since the way it's set up is weird (it's a single string where just the rendered text changes). I could probably work something in for this, though.

**Comment by gpakosz** [comment]
Are you saying it's a single string but you alter the font size for the modifier part?

**Comment by PandorasFox** [comment]
Sorry, I meant to say that it's a single text-widget thing where just the rendered text changes (by using a different single string depending on the unlock state)

it shouldn't take me long to do this once I start on it, but I'm a bit swamped with coursework at the moment p:

**Comment by PandorasFox** [comment]
`--verif-text` and `--modif-text` are in dev @ dd44aab1bd68368fd3d97145427c84d950015e34. Please give them a poke - they should be fine.

**Comment by PandorasFox** [comment]
This is in master now. I don't think there's any bugs with this (feel free to reopen this issue if there are any, though)

**Comment by gpakosz** [comment]
Will try. Should the `i3lock-color-git` AUR package bring these changes?

**Comment by PandorasFox** [comment]
Yep.

**Comment by gpakosz** [comment]
Thanks

**Comment by gpakosz** [comment]
Sorry for the late test, the lock icon is still not centered. I'm using `i3lock-color-git r483.e07c3f0-1`

**Comment by PandorasFox** [comment]
I'll need more details. How is it not centered?

You can set the veriy/wrong/modifier text positions individually, so alignment is up to you.

**Comment by gpakosz** [comment]
It's not aligned the same way as my original screenshot.

But I managed to use `--verifpos='w/2:h/2+r/3'` 👌. Not so portable but does the job
