### ISSUE TITLE
Ability to set empty text strings

### ISSUE THREAD

**Issue by gpakosz** [Raymo111/i3lock-color#83]
In particular, I would like to have a way to set `--noinputtext` to the empty string so that nothing happens when hitting the backspace more times than the number of characters entered.

This would emulate behavior prior to the introduction of the `--noinputtext` option.

**Comment by PandorasFox** [comment]
I think you should already be able to do this (i.e. `--noinputtext=""`), but I'd have to check. It's just that the option has a required argument so you should just have to specify empty string.

**Comment by gpakosz** [comment]
Oh you're right. Though, locking, then e.g. hitting backspace while there's no input still flashes the ring while the stable build I tried didn't

**Comment by PandorasFox** [comment]
It'll still color the ring to the no input/backspace highlight even when there's no input. Not really anything I can do about that since that's an upstream behaviour I don't intend on changing.
