### ISSUE TITLE
Make it possible to configure "no input" text.

### ISSUE THREAD

**Issue by crocket** [Raymo111/i3lock-color#86]
When I press backspace, I see "no input". I want to be able to configure "no input" text so that I can make it disappear.

Currently, wrong text and verification text are disabled with `--veriftext="" --wrongtext=""`.

**Comment by PandorasFox** [comment]
`--noinputtext=""`

**Comment by crocket** [comment]
I'm using `2.10.1-2-c` which doesn't have `--noinputtext=` option.
Do I need a more recent version?

**Comment by PandorasFox** [comment]
Yeah, it was added in 778745684561288e16592159e6e1ed21b83f1b96. I'll go make another release, I guess.

**Comment by PandorasFox** [comment]
Alright, I made another release (2.11-c), so you should be able to use that just fine now.

**Comment by crocket** [comment]
Thank you.

**Comment by crocket** [comment]
What is `-c`? When I package it for Gentoo Linux, it seems impossible to translate `-c` into something that gentoo understands.

**Comment by PandorasFox** [comment]
I tag my releases with the `-c` suffix so as to not conflict with upstream's tagged releases, pretty much. One of the (many) problems that've come up when trying to introduce new stuff and staying as just a superset of the base i3lock.
