### ISSUE TITLE
Automatically shuts down the monitor after a configurable amount of seconds

### ISSUE THREAD

**Issue by pavanjadhaw** [Raymo111/i3lock-color#87]
**Enhancement**  
  
As i3lock now keeps monitor on.
Will it be possible to automatically shuts down the monitor after a configurable amount of seconds.  
The monitor will automatically be activated by pressing a key or moving the mouse and the password can be entered then.

**Comment by bew** [comment]
What do you mean by ` i3lock now keeps monitor on` ? For me it doesn't do that.
Btw, this is a X's setting (called [DPMS](https://wiki.archlinux.org/index.php/Display_Power_Management_Signaling)), not i3lock's.

You can see if it's activated or not with `xset q`, at the bottom. Mine looks like:
```
DPMS (Energy Star):
  Standby: 600    Suspend: 600    Off: 600
  DPMS is Enabled
  Monitor is On
```
So the display will turn off after 600 seconds (10 minutes).

**Comment by PandorasFox** [comment]
i3lock doesn't keep my monitor on. Check your DPMS/X settings, as @bew mentioned.

**Comment by pavanjadhaw** [comment]
Yeah that fixed it. Thanks.  
I should have researched a little before opening a issue.
