### ISSUE TITLE
Cannot parse cw and ch in datepos

### ISSUE THREAD

**Issue by YodaEmbedding** [Raymo111/i3lock-color#89]
The following:

    i3lock --datepos="x+ix-(0.5*cw):y+iy-(0.5*ch)+40"

Gives:

> Failed to reason about 'x+ix-(0.5*cw)' given by '--datepos'

Were `cw` and `ch` removed? They seem like useful functionality.

**Comment by YodaEmbedding** [comment]
Nevermind, looks like they were renamed to `w` and `h`.

**Comment by PandorasFox** [comment]
sorta. ch/cw don't exist anymore, since the clock canvas isn't static, and instead the clock stuff is painted directly onto the main canvas (mostly to speed up draw cycles)
