### ISSUE TITLE
make fail on linuxmint 18

### ISSUE THREAD

**Issue by eseca** [Raymo111/i3lock-color#9]
Hi. Trying to install on linuxmint 18

```
 sudo aptitude install pkg-config libxcb1 libpam-dev libcairo-dev libxcb-xinerama0-dev libev-dev libx11-dev libx11-xcb-dev libxkbcommon0 libxkbcommon-x11-0 libxcb-dpms0-dev libxcb-image0-dev libxcb-util0-dev libxcb-xkb-dev libxkbcommon-x11-dev
```

Then I cloned and cd to the project. 

```
$ make 
Package xkbcommon was not found in the pkg-config search path.
Perhaps you should add the directory containing `xkbcommon.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xkbcommon' found
Package xkbcommon was not found in the pkg-config search path.
Perhaps you should add the directory containing `xkbcommon.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xkbcommon', required by 'xkbcommon-x11', not found
cc -std=c99 -pipe -Wall  -D_GNU_SOURCE -DXKBCOMPOSE=0 -DVERSION=\""2.7-55-g87ba982 (2016-10-01)"\"  -c -o i3lock.o i3lock.c
i3lock.c:26:33: fatal error: xkbcommon/xkbcommon.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'i3lock.o' failed
make: *** [i3lock.o] Error 1
```

**Comment by PandorasFox** [comment]
You need to make sure that the compiler can find xcbcommon by making sure pkgconfig is exported properly. 

I had a similar problem with a different thing I was compiling not too long ago on Arch; this isn't a mint or i3lock-color problem.

**Comment by eseca** [comment]
Sorry. I don't know how to do that. Can you explain it to me, please?

**Comment by PandorasFox** [comment]
You'll need to figure out what directory `xkbcommon` is installed to on mint (you'll need to use `aptitude` to query the packages and see where they're installed to on Mint; I use Arch so I don't know where they're packaged to off the top of my head). 

After that, you'll need to (update the PKG_CONFIG_PATH env var to contain the directory that `xkbcommon`'s libs are in)[http://askubuntu.com/questions/210210/pkg-config-path-environment-variable] and properly export it, usually in your xsessionrc, or just manually export it immediately before building.

You'll want to look into environment variables, exporting them for a session, and making sure you're properly exporting the correct directory for the `xkbcommon` package libs. I'm not really the best person to explain all of these in detail, and google/stackoverflow/reddit would be better tools to ask.
