### ISSUE TITLE
ASan runtime does not come first in initial library list

### ISSUE THREAD

**Issue by 2secslater** [Raymo111/i3lock-color#90]
This is what I see on my screen whenever I try to run the i3lock command:
`==11982==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.`

This has been happening since I upgraded to Ubuntu Bionic.

**Comment by PandorasFox** [comment]
How are you compiling i3lock? Sounds like you're not building a release build for day-today use. ASAN shouldn't be enabled in those.

That'll be an issue in some other lib (i.e. fontconfig) not having ASAN linked and not having it loaded. This isn't an i3lock issue.

**Comment by 2secslater** [comment]
I'm compiling it with the code provided on the "Building" section of the readme:
`autoreconf -i && ./configure && make`

**Comment by PandorasFox** [comment]
Check the paragraph directly above that about tagging for non-debug builds
