### ISSUE TITLE
Release Version Naming

### ISSUE THREAD

**Issue by ianhattendorf** [Raymo111/i3lock-color#92]
Would it be possible to modify the release naming template going forward? Hyphens are incompatible with rpms/debs. Maybe something like `2.11.c` instead of `2.11-c`?

**Comment by PandorasFox** [comment]
Hm, sounds reasonable. The next release I make (there might be a point release in the next couple weeks) will probably be like `2.11.c` or `2.11.c.1` - I'm still unsure if I want to keep to the same major version # that upstream uses, or if I want to just break off.

(I'll keep this open until my next release so I don't forget)

**Comment by ianhattendorf** [comment]
Sounds like a plan, thanks. I would say if you do a point release then go with `2.11.c.1` to avoid repeating a version. Basically, you just never want to go backwards or have a duplicate version.

Tracking upstream's version is definitely helpful, but depending on how much changes it may start to lose its meaning so I can see either way there.

**Comment by PandorasFox** [comment]
Yeah, definitely. I've been super on the fence about keeping the version numbers in-line with upstream - on the one hand, it's handy to tell if I've merged upstream's latest stuff yet, but on the other hand, it becomes kinda a pain to make i3lock-color releases that aren't related to upstream releases (and I want to avoid future naming conflicts, so just appending a -c seemed the easiest at the time... oops)

**Comment by PandorasFox** [comment]
Fixed in the latest release. Sorry about the delay in release; my internship this summer kept me tired & busy.
