### ISSUE TITLE
gcc-libs 8.1.0-1 dependency

### ISSUE THREAD

**Issue by ghost** [Raymo111/i3lock-color#93]
`i3lock: error while loading shared libraries: libasan.so.4: cannot open shared object file: No such file or directory`

`$ pacman -Qlq gcc-libs | grep asan
/usr/lib/libasan.so
/usr/lib/libasan.so.5
/usr/lib/libasan.so.5.0.0
`

**Comment by PandorasFox** [comment]
Yeah, that's literally a dependency of gcc and it's also provided by clang. We already depend on gcc, so as long as you have all of gcc's deps, it'll work fine.

Also, ASAN is only needed for debugging and not for everyday usage.

**Comment by PandorasFox** [comment]
Like, no specific CC is listed as a dep, because both gcc and clang provide ASAN, and it's pretty expected for a C project that you have a C compiler of your choice. It's not a build dep to have a compiler.

**Comment by ghost** [comment]
It was a mistake on my part using the wrong technical term. The error started to appear after gcc was updated. Building the package again fixed the issue.

**Comment by PandorasFox** [comment]
Yeah, unfortunately there's no real way to signal what packages need to be rebuilt on other package updates, but at the same time, it shouldn't be an issue since ASAN shouldn't be enabled in persistent builds
