### ISSUE TITLE
Memory leak after gcc upgrade.

### ISSUE THREAD

**Issue by Ludvins** [Raymo111/i3lock-color#94]
After upgrating gcc to 8.10 i3lock-color doesnt work properly and produces memory leaks.
![memory leak](https://user-images.githubusercontent.com/17424381/40370188-ffd3b090-5ddf-11e8-8756-3e829d7466c6.png)

**Comment by PandorasFox** [comment]
#88 

this is actually a known fontconfig issue.

also, check the readme's steps on building and build release versions and not debug versions.
