### ISSUE TITLE
Respect Xft.dpi for HiDPI Screens

### ISSUE THREAD

**Issue by medoix** [Raymo111/i3lock-color#95]
Any chance of getting support for Xft.dpi as default?

https://github.com/i3/i3lock/issues/184

**Comment by PandorasFox** [comment]
My desktop is in storage back at my University while I'm across the country for an internship this summer, so I don't really have a Dev environment currently. I'll accept pulls/patches, but I won't be able to do it myself for a few weeks at the least.

(My only computer currently is a work machine, which, uh, I don't want my employer to then own this project if I use that laptop for updating this with company resources)

**Comment by medoix** [comment]
I have been attempting to look at the changes upstream in the i3lock project but i cant get it to make. I will continue trying to get it to work.

**Comment by PandorasFox** [comment]
Eh, theoretically I'll be getting a laptop with a 4K display pretty soon, which will actually be exactly what I need for testing this stuff. I wouldn't be able to verify anything until then, anyways.

**Comment by PandorasFox** [comment]
did this on a flight earlier today and I'm pretty sure it's working fine now, though I still don't actually have any high dpi devices to test on.

if anyone can test and confirm this works as expected, that'd be great (or confirm difference from before merge/after merge)

**Comment by skalyan91** [comment]
I have a HiDPI laptop screen and can confirm that there are no scaling issues (aside from the minor one I’ve mentioned in https://github.com/PandorasFox/i3lock-color/issues/103).
